import { useState } from 'react'
import { getCompany, getJobs, saveCompany, saveJobs } from '../../services/companyService'
import { canTransition, getAllApplications, updateApplication } from '../../services/applicationService'

function Shell({ title, description, children }) { return <section><h1 className="text-2xl font-extrabold text-[#172d50]">{title}</h1><p className="mt-1 mb-5 text-sm text-[#7890ad]">{description}</p>{children}</section> }
export function CompanyProfilePage() { const [company, setCompany] = useState(getCompany()); const [saved, setSaved] = useState(false); function submit(e) { e.preventDefault(); saveCompany(company); setSaved(true) } return <Shell title="Hồ sơ doanh nghiệp" description="Quản lý thông tin công khai và hồ sơ pháp lý doanh nghiệp."><form onSubmit={submit} className="rounded-xl border border-[#e1eaf5] bg-white p-6">{[['name','Tên doanh nghiệp'],['email','Email'],['taxCode','Mã số thuế'],['industry','Lĩnh vực'],['address','Địa chỉ']].map(([field,label]) => <label key={field} className="mb-4 block text-sm font-semibold text-[#2b4263]">{label}<input value={company[field]} onChange={(e) => setCompany({ ...company, [field]: e.target.value })} className="mt-2 w-full rounded-md border border-[#d8e3f0] px-3 py-2.5 font-normal" /></label>)}<label className="block text-sm font-semibold text-[#2b4263]">Giới thiệu<textarea value={company.description} onChange={(e) => setCompany({ ...company, description: e.target.value })} className="mt-2 min-h-28 w-full rounded-md border border-[#d8e3f0] p-3 font-normal" /></label>{saved && <p className="mt-3 text-sm font-semibold text-green-600">Đã lưu hồ sơ doanh nghiệp.</p>}<button className="mt-4 rounded-md bg-[#0757c9] px-5 py-3 text-sm font-bold text-white" type="submit">Lưu thay đổi</button></form></Shell> }
export function CompanyJobsPage({ create = false }) { const [jobs, setJobs] = useState(getJobs()); const [form, setForm] = useState({ title: '', location: '', skills: '' }); function submit(e) { e.preventDefault(); const next = [...jobs, { id: Date.now(), companyId: 2, title: form.title, location: form.location, skills: form.skills.split(',').map((x) => x.trim()).filter(Boolean), status: 'Đang tuyển', applicants: 0 }]; setJobs(saveJobs(next)); setForm({ title: '', location: '', skills: '' }) } if (create) return <Shell title="Đăng tin tuyển dụng" description="Tạo vị trí thực tập mới cho sinh viên."><form onSubmit={submit} className="max-w-2xl rounded-xl border border-[#e1eaf5] bg-white p-6">{[['title','Tên vị trí'],['location','Địa điểm'],['skills','Kỹ năng, cách nhau bằng dấu phẩy']].map(([field,label]) => <label key={field} className="mb-4 block text-sm font-semibold text-[#2b4263]">{label}<input required value={form[field]} onChange={(e) => setForm({ ...form, [field]: e.target.value })} className="mt-2 w-full rounded-md border border-[#d8e3f0] px-3 py-2.5 font-normal" /></label>)}<button className="rounded-md bg-[#0757c9] px-5 py-3 text-sm font-bold text-white" type="submit">Đăng tin</button></form></Shell>; return <Shell title="Tin tuyển dụng" description="Theo dõi các vị trí đang đăng tuyển."><div className="space-y-4">{jobs.map((job) => <article className="rounded-xl border border-[#e1eaf5] bg-white p-5" key={job.id}><div className="flex flex-wrap justify-between gap-3"><div><h2 className="font-bold text-[#172d50]">{job.title}</h2><p className="mt-1 text-sm text-[#7890ad]">{job.location} · {job.applicants} hồ sơ</p></div><span className="h-fit rounded-full bg-green-50 px-3 py-1 text-xs font-bold text-green-700">{job.status}</span></div><div className="mt-3 flex gap-2">{job.skills.map((skill) => <span className="rounded-full bg-[#edf4ff] px-2 py-1 text-xs text-[#4774b3]" key={skill}>{skill}</span>)}</div></article>)}</div></Shell> }
export function CompanyApplicationsPage() { const [applications, setApplications] = useState(getAllApplications()); const rows = applications.map((app) => ({ ...app, name: 'Nguyễn Minh Anh', position: app.internshipId === 1 ? 'Frontend Developer Intern' : 'Business Analyst Intern' })); function change(id, status, statusLabel) { setApplications(updateApplication(id, { status, statusLabel })) } return <Shell title="Hồ sơ ứng viên" description="Xem, lọc và xử lý hồ sơ sinh viên ứng tuyển."><div className="overflow-x-auto rounded-xl border border-[#e1eaf5] bg-white"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-[#f5f8fc] text-xs uppercase text-[#7890ad]"><tr><th className="p-4">Ứng viên</th><th className="p-4">Vị trí</th><th className="p-4">Trạng thái</th><th className="p-4">Thao tác</th></tr></thead><tbody>{rows.map((app) => <tr className="border-t border-[#edf1f6]" key={app.id}><td className="p-4 font-semibold text-[#172d50]">{app.name}</td><td className="p-4 text-[#526b8d]">{app.position}</td><td className="p-4"><span className="rounded-full bg-amber-50 px-2 py-1 text-xs font-bold text-amber-700">{app.statusLabel}</span></td><td className="flex gap-2 p-4"><button disabled={!canTransition(app.status, '06')} className="rounded-md bg-[#0757c9] px-3 py-2 text-xs font-bold text-white disabled:bg-slate-300" onClick={() => change(app.id, '06', 'Mời phỏng vấn')} type="button">Mời phỏng vấn</button><button disabled={!canTransition(app.status, '08')} className="rounded-md border border-red-200 px-3 py-2 text-xs font-bold text-red-600 disabled:border-slate-200 disabled:text-slate-300" onClick={() => change(app.id, '08', 'Không đạt')} type="button">Từ chối</button></td></tr>)}</tbody></table></div></Shell> }
export function CompanyInterviewsPage() { return <Shell title="Lịch phỏng vấn" description="Quản lý lịch phỏng vấn và trạng thái tham dự."><div className="rounded-xl border border-dashed border-[#b9cee8] bg-white p-10 text-center"><h2 className="font-bold text-[#172d50]">Chưa có lịch sắp tới</h2><p className="mt-2 text-sm text-[#7890ad]">Lịch phỏng vấn sẽ được tạo từ màn hình xử lý ứng viên.</p></div></Shell> }
export function CompanyInternsPage() { return <Shell title="Sinh viên đang thực tập" description="Theo dõi danh sách sinh viên đã xác nhận nhận thực tập."><Empty /></Shell> }
export function CompanyEvaluationsPage() { return <Shell title="Đánh giá sinh viên" description="Ghi nhận đánh giá năng lực và kết quả cuối kỳ."><Empty /></Shell> }
function Empty() { return <div className="rounded-xl border border-dashed border-[#b9cee8] bg-white p-10 text-center text-sm text-[#7890ad]">Chưa có dữ liệu cần xử lý.</div> }
