import { useState } from 'react'
import students from '../../data/applications.json'

function Shell({ title, description, children }) { return <section><h1 className="text-2xl font-extrabold text-[#172d50]">{title}</h1><p className="mt-1 mb-5 text-sm text-[#7890ad]">{description}</p>{children}</section> }
export function LecturerStudentsPage() { return <Shell title="Sinh viên được phân công" description="Danh sách sinh viên thuộc phạm vi hướng dẫn của bạn."><Table rows={students.map((x) => ({ name: 'Nguyễn Minh Anh', internship: `Hồ sơ #${x.id}`, status: x.statusLabel }))} /></Shell> }
export function LecturerInternshipsPage() { return <Shell title="Theo dõi tiến độ thực tập" description="Theo dõi các mốc tiến độ và sinh viên có nguy cơ chậm tiến độ."><div className="grid gap-4 sm:grid-cols-3">{[['Đang thực tập','8'],['Cần cập nhật','4'],['Hoàn thành','0']].map(([label,value]) => <div className="rounded-xl border border-[#e1eaf5] bg-white p-5" key={label}><p className="text-sm text-[#7890ad]">{label}</p><p className="mt-2 text-3xl font-extrabold text-[#0757c9]">{value}</p></div>)}</div></Shell> }
export function LecturerDiariesPage() { const [comment, setComment] = useState(''); const [saved, setSaved] = useState(false); return <Shell title="Nhật ký thực tập" description="Xem nhật ký và ghi nhận nhận xét trong kỳ."><div className="rounded-xl border border-[#e1eaf5] bg-white p-5"><p className="text-xs font-bold text-[#7890ad]">Nguyễn Minh Anh · Tuần 1</p><p className="mt-2 text-sm text-[#2b4263]">Hoàn thành thiết kế giao diện trang danh sách cơ hội.</p><textarea className="mt-4 w-full rounded-md border border-[#d8e3f0] p-3 text-sm" placeholder="Nhập nhận xét..." value={comment} onChange={(e) => setComment(e.target.value)} />{saved && <p className="mt-2 text-sm font-semibold text-green-600">Đã lưu nhận xét.</p>}<button onClick={() => setSaved(true)} className="mt-3 rounded-md bg-[#0757c9] px-4 py-2 text-sm font-bold text-white" type="button">Lưu nhận xét</button></div></Shell> }
export function LecturerReportsPage() { return <Shell title="Báo cáo cần duyệt" description="Kiểm tra và phản hồi báo cáo tổng kết của sinh viên."><Empty text="Chưa có báo cáo chờ duyệt." /></Shell> }
export function LecturerEvaluationsPage() { const [score, setScore] = useState(''); const [saved, setSaved] = useState(false); return <Shell title="Đánh giá cuối kỳ" description="Chấm điểm và ký xác nhận kết quả thực tập."><div className="max-w-xl rounded-xl border border-[#e1eaf5] bg-white p-5"><p className="font-bold text-[#172d50]">Nguyễn Minh Anh</p><label className="mt-5 block text-sm font-semibold text-[#2b4263]">Điểm tổng kết<input type="number" min="0" max="10" value={score} onChange={(e) => setScore(e.target.value)} className="mt-2 w-full rounded-md border border-[#d8e3f0] px-3 py-2.5" /></label><button onClick={() => setSaved(true)} className="mt-4 rounded-md bg-[#0757c9] px-4 py-2 text-sm font-bold text-white" type="button">Lưu đánh giá</button>{saved && <p className="mt-3 text-sm font-semibold text-green-600">Đánh giá đã lưu ở trạng thái nháp.</p>}</div></Shell> }
function Table({ rows }) { return <div className="overflow-x-auto rounded-xl border border-[#e1eaf5] bg-white"><table className="w-full min-w-[560px] text-left text-sm"><thead className="bg-[#f5f8fc] text-xs uppercase text-[#7890ad]"><tr><th className="p-4">Sinh viên</th><th className="p-4">Hồ sơ</th><th className="p-4">Trạng thái</th></tr></thead><tbody>{rows.map((row, index) => <tr className="border-t border-[#edf1f6]" key={index}><td className="p-4 font-semibold text-[#172d50]">{row.name}</td><td className="p-4 text-[#526b8d]">{row.internship}</td><td className="p-4 text-[#0757c9]">{row.status}</td></tr>)}</tbody></table></div> }
function Empty({ text }) { return <div className="rounded-xl border border-dashed border-[#b9cee8] bg-white p-10 text-center text-sm text-[#7890ad]">{text}</div> }
