import { useState } from 'react'
import { Link } from 'react-router'
import { getSession } from '../../services/mockAuth'
import { getCompany, getJobs, saveCompany, saveJobs } from '../../services/companyService'
import { getAllApplications, getApplicationCompanyId, updateApplication } from '../../services/applicationService'
import { createInterview, getInterviews, recordInterviewResult } from '../../services/interviewService'
import { getRecords } from '../../services/internshipRecordService'
import { getEvaluations, saveEvaluation } from '../../services/evaluationService'
import { INTERNSHIP_STATUSES } from '../../constants/internshipStatuses'
import users from '../../data/users.json'

const inputClass = 'mt-2 w-full rounded-md border border-[#d8e3f0] px-3 py-2.5 text-sm'
const buttonClass = 'rounded-md bg-[#0757c9] px-4 py-2.5 text-sm font-bold text-white disabled:bg-slate-300'
function Shell({ title, children }) { return <section><div className="dashboard-page-heading"><div><p className="dashboard-eyebrow">DOANH NGHIỆP</p><h1>{title}</h1></div></div>{children}</section> }
function Notice({ text }) { return text && <p role="status" className="mb-4 rounded-md bg-[#edf4ff] p-3 text-sm text-[#123a8b]">{text}</p> }
const ownApps = () => getAllApplications().filter((app) => getApplicationCompanyId(app) === getSession()?.id)
const studentName = (id) => users.find((user) => user.id === id)?.name || `Sinh viên #${id}`

export function CompanyProfilePage() {
  const session = getSession(); const [company, setCompany] = useState(getCompany()); const [saved, setSaved] = useState(false)
  function submit(event) { event.preventDefault(); saveCompany({ ...company, id: session.id }); setSaved(true) }
  return <Shell title="Hồ sơ doanh nghiệp"><form className="max-w-2xl space-y-4 rounded-xl border bg-white p-6" onSubmit={submit}>{['name', 'email', 'taxCode', 'industry', 'address', 'description'].map((field) => <label className="block text-sm font-semibold" key={field}>{({ name: 'Tên doanh nghiệp', email: 'Email', taxCode: 'Mã số thuế', industry: 'Lĩnh vực', address: 'Địa chỉ', description: 'Giới thiệu' })[field]}<input className={inputClass} value={company[field] || ''} onChange={(event) => setCompany({ ...company, [field]: event.target.value })} /></label>)}<p className="text-sm">Trạng thái: {company.status || 'Đã duyệt'}</p><button className={buttonClass}>Lưu thay đổi</button>{saved && <p role="status">Đã lưu hồ sơ.</p>}</form></Shell>
}

export function CompanyJobsPage({ create = false }) {
  const [jobs, setJobs] = useState(getJobs()); const [message, setMessage] = useState(''); const [form, setForm] = useState({ title: '', location: '', skills: '', salary: '', mode: 'Tại văn phòng', deadline: '' }); const mine = jobs.filter((job) => job.companyId === getSession()?.id)
  function submit(event) { event.preventDefault(); const company = getCompany(); if (company.status && company.status !== 'Đã duyệt') { setMessage('Doanh nghiệp chưa được duyệt'); return } const next = [...jobs, { ...form, id: Date.now(), companyId: getSession().id, skills: form.skills.split(',').map((skill) => skill.trim()).filter(Boolean), status: 'Bản nháp' }]; setJobs(saveJobs(next)); setMessage('Đã tạo bản nháp. Xuất bản để hiển thị công khai.') }
  function toggle(job) { if (!window.confirm(job.status === 'Đã xuất bản' ? 'Đóng tin này?' : 'Xuất bản tin này?')) return; setJobs(saveJobs(jobs.map((item) => item.id === job.id ? { ...item, status: job.status === 'Đã xuất bản' ? 'Đã đóng' : 'Đã xuất bản' } : item))) }
  if (create) return <Shell title="Đăng tin tuyển dụng"><Notice text={message} /><form className="max-w-2xl space-y-4 rounded-xl border bg-white p-6" onSubmit={submit}>{[['title', 'Vị trí'], ['location', 'Địa điểm'], ['skills', 'Kỹ năng, phân cách dấu phẩy'], ['salary', 'Mức hỗ trợ'], ['deadline', 'Hạn ứng tuyển']].map(([field, label]) => <label className="block text-sm font-semibold" key={field}>{label}<input required className={inputClass} type={field === 'deadline' ? 'date' : 'text'} value={form[field]} onChange={(event) => setForm({ ...form, [field]: event.target.value })} /></label>)}<label className="block text-sm font-semibold">Hình thức<select className={inputClass} value={form.mode} onChange={(event) => setForm({ ...form, mode: event.target.value })}><option>Tại văn phòng</option><option>Hybrid</option><option>Remote</option></select></label><button className={buttonClass}>Lưu bản nháp</button></form></Shell>
  return <Shell title="Tin tuyển dụng"><Link className={buttonClass} to="/company/jobs/create">Tạo tin mới</Link><div className="mt-6 space-y-3">{mine.map((job) => <article className="flex flex-wrap items-center justify-between gap-3 rounded-xl border bg-white p-5" key={job.id}><div><h2 className="font-bold">{job.title}</h2><p className="text-sm text-[#6684a8]">{job.location} · {job.status}</p></div><button className={buttonClass} onClick={() => toggle(job)} type="button">{job.status === 'Đã xuất bản' ? 'Đóng tin' : 'Xuất bản'}</button></article>)}</div></Shell>
}

export function CompanyApplicationsPage() {
  const [apps, setApps] = useState(ownApps()); const [message, setMessage] = useState(''); const [selected, setSelected] = useState(null); const [form, setForm] = useState({ date: '', time: '', mode: 'Online', location: '' })
  function advance(app, status) { const response = updateApplication(app.id, { status }, { action: status === '05' ? 'Tiếp nhận hồ sơ' : 'Xử lý hồ sơ' }); setMessage(response.ok ? 'Đã cập nhật hồ sơ.' : response.error); setApps(ownApps()) }
  function invite(event) { event.preventDefault(); const response = createInterview({ ...form, applicationId: selected.id }); setMessage(response.ok ? 'Đã gửi lịch phỏng vấn.' : response.error); if (response.ok) setSelected(null); setApps(ownApps()) }
  return <Shell title="Hồ sơ ứng viên"><Notice text={message} /><div className="space-y-3">{apps.map((app) => <article className="flex flex-wrap items-center justify-between gap-3 rounded-xl border bg-white p-5" key={app.id}><div><h2 className="font-bold">{studentName(app.studentId)} · Hồ sơ #{app.id}</h2><p className="text-sm text-[#6684a8]">{INTERNSHIP_STATUSES.find((item) => item.id === app.status)?.label}{app.closureReason && ` · Đã đóng: ${app.closureReason}`}</p></div><div className="flex gap-2">{app.status === '04' && <button className={buttonClass} onClick={() => advance(app, '05')}>Tiếp nhận</button>}{app.status === '05' && !app.closureReason && <button className={buttonClass} onClick={() => setSelected(app)}>Mời phỏng vấn</button>}</div></article>)}</div>{selected && <form onSubmit={invite} className="mt-5 space-y-3 rounded-xl border bg-white p-5"><h2 className="font-bold">Mời {studentName(selected.studentId)} phỏng vấn</h2>{[['date', 'Ngày'], ['time', 'Giờ'], ['location', 'Địa điểm hoặc liên kết']].map(([field, label]) => <label className="block text-sm" key={field}>{label}<input required className={inputClass} type={field === 'date' ? 'date' : field === 'time' ? 'time' : 'text'} value={form[field]} onChange={(event) => setForm({ ...form, [field]: event.target.value })} /></label>)}<label className="block text-sm">Hình thức<select className={inputClass} value={form.mode} onChange={(event) => setForm({ ...form, mode: event.target.value })}><option>Online</option><option>Offline</option></select></label><div className="flex gap-2"><button className={buttonClass}>Gửi lịch</button><button type="button" onClick={() => setSelected(null)}>Hủy</button></div></form>}</Shell>
}

export function CompanyInterviewsPage() {
  const [items, setItems] = useState(getInterviews()); const [message, setMessage] = useState(''); const mine = items.filter((item) => item.companyId === getSession()?.id)
  function record(id, passed) { const note = window.prompt('Ghi nhận xét kết quả phỏng vấn:') || ''; if (!note.trim()) { setMessage('Cần nhập nhận xét'); return } const response = recordInterviewResult(id, passed, note); setItems(response.interviews); setMessage(response.ok ? 'Đã ghi nhận kết quả.' : response.error) }
  return <Shell title="Lịch phỏng vấn"><Notice text={message} /><div className="space-y-3">{mine.map((item) => <article className="flex flex-wrap items-center justify-between gap-3 rounded-xl border bg-white p-5" key={item.id}><div><h2 className="font-bold">{studentName(item.studentId)} · Hồ sơ #{item.applicationId}</h2><p className="text-sm text-[#6684a8]">{item.date} {item.time} · {item.location} · {item.status}</p></div>{item.status === 'Đã xác nhận' && <div className="flex gap-2"><button className={buttonClass} onClick={() => record(item.id, true)}>Đạt</button><button className="rounded-md border px-4 py-2 text-sm" onClick={() => record(item.id, false)}>Không đạt</button></div>}</article>)}</div></Shell>
}

export function CompanyInternsPage() { const apps = ownApps().filter((app) => ['11', '12', '13', '14', '15'].includes(app.status)); return <Shell title="Sinh viên thực tập"><p className="mb-4 text-sm">{apps.length} sinh viên</p><div className="space-y-3">{apps.map((app) => <article className="rounded-xl border bg-white p-5" key={app.id}>{studentName(app.studentId)} · {INTERNSHIP_STATUSES.find((item) => item.id === app.status)?.label}</article>)}</div></Shell> }

export function CompanyEvaluationsPage() {
  const [items, setItems] = useState(getEvaluations()); const [score, setScore] = useState({}); const [message, setMessage] = useState(''); const records = getRecords().filter((item) => item.companyId === getSession()?.id && item.status === 'Đang thực tập')
  function submit(record) { const response = saveEvaluation({ applicationId: record.applicationId, studentId: record.studentId, evaluatorRole: 'company', score: score[record.id] }); setItems(response.evaluations); setMessage(response.ok ? 'Đánh giá đã gửi và khóa.' : response.error) }
  return <Shell title="Đánh giá sinh viên"><Notice text={message} /><div className="space-y-3">{records.map((record) => { const locked = items.some((item) => item.applicationId === record.applicationId && item.evaluatorRole === 'company'); return <article className="rounded-xl border bg-white p-5" key={record.id}><h2 className="font-bold">{studentName(record.studentId)} · {record.position}</h2><label className="mt-3 block text-sm">Điểm 0–10<input className={inputClass} type="number" min="0" max="10" value={score[record.id] ?? ''} disabled={locked} onChange={(event) => setScore({ ...score, [record.id]: event.target.value })} /></label><button className={`${buttonClass} mt-3`} disabled={locked || score[record.id] === undefined} onClick={() => submit(record)}>{locked ? 'Đã khóa' : 'Gửi đánh giá'}</button></article> })}</div></Shell>
}
