import { useState } from 'react'
import CompanyRegistrationForm from '../components/CompanyRegistrationForm'
import { PublicLayout, PageHero } from '../components/ui/PageUI'

import { forgotPasswordRequest, resetPasswordRequest } from '../api/authApi'
import { lookupCompany } from '../api/publicApi'

function Shell({title,children}){return <PublicLayout><PageHero eyebrow="TÀI KHOẢN & KẾT NỐI" title={title} description="Hoàn thiện thông tin để tiếp tục hành trình cùng InternConnect."/><div className="site-container section-space auth-service-content">{children}</div></PublicLayout>}
const fieldClass = 'mt-2 w-full rounded-md border border-line px-3 py-3 text-sm'
const actionClass = 'rounded-md bg-primary px-5 py-3 text-sm font-bold text-white'
export function ForgotPasswordPage(){const[message,setMessage]=useState('');async function submit(event){event.preventDefault();try{const result=await forgotPasswordRequest(new FormData(event.currentTarget).get('email'));setMessage(result.resetToken?`Token development: ${result.resetToken}`:'Nếu email tồn tại, hướng dẫn đặt lại mật khẩu đã được gửi.')}catch(error){setMessage(error.response?.data?.error?.message||'Không thể gửi yêu cầu.')}}return <Shell title="Quên mật khẩu"><form className="space-y-4 rounded-xl border bg-white p-6" onSubmit={submit}><label className="block text-sm font-semibold">Email<input className={fieldClass} type="email" name="email" required/></label><button className={actionClass}>Gửi yêu cầu</button>{message&&<p role="status" className="text-sm">{message}</p>}</form></Shell>}
export function ResetPasswordPage(){const[message,setMessage]=useState('');async function submit(event){event.preventDefault();const values=Object.fromEntries(new FormData(event.currentTarget));if(values.password!==values.confirmPassword){setMessage('Xác nhận mật khẩu không khớp.');return}try{await resetPasswordRequest(values.token,values.password);setMessage('Đặt lại mật khẩu thành công. Bạn có thể đăng nhập.')}catch(error){setMessage(error.response?.data?.error?.message||'Không thể đặt lại mật khẩu.')}}return <Shell title="Đặt lại mật khẩu"><form className="space-y-4 rounded-xl border bg-white p-6" onSubmit={submit}><label className="block text-sm font-semibold">Token<input className={fieldClass} name="token" required/></label><label className="block text-sm font-semibold">Mật khẩu mới<input className={fieldClass} type="password" name="password" minLength="8" required/></label><label className="block text-sm font-semibold">Xác nhận mật khẩu<input className={fieldClass} type="password" name="confirmPassword" minLength="8" required/></label><button className={actionClass}>Đặt lại mật khẩu</button>{message&&<p role="status" className="text-sm">{message}</p>}</form></Shell>}
export function CompanyRegisterPage() { return <Shell title="Đăng ký doanh nghiệp"><CompanyRegistrationForm/></Shell> }
export function CompanyLookupPage(){const[query,setQuery]=useState(''),[found,setFound]=useState(null),[message,setMessage]=useState('');async function submit(event){event.preventDefault();try{setFound(await lookupCompany(query));setMessage('')}catch(error){setFound(null);setMessage(error.response?.data?.error?.message||'Không thể tra cứu hồ sơ.')}}return <Shell title="Tra cứu hồ sơ doanh nghiệp"><form className="flex flex-wrap gap-3 rounded-xl border bg-white p-6" onSubmit={submit}><label className="min-w-0 flex-1 text-sm">Mã hồ sơ, mã số thuế hoặc email<input required className={fieldClass} value={query} onChange={event=>setQuery(event.target.value)}/></label><button className={`${actionClass} self-end`}>Tra cứu</button></form>{(found||message)&&<div className="mt-4 rounded-xl border bg-white p-6 text-sm">{found?<><b>{found.name}</b><p>Trạng thái: {found.status}</p>{found.rejection_reason&&<p>Lý do: {found.rejection_reason}</p>}</>:message}</div>}</Shell>}
