import { useState } from 'react'
import { Link } from 'react-router'
import Header from '../components/Header/Header'
import Footer from '../components/Footer/Footer'
import { forgotPasswordRequest, registerCompanyRequest, resetPasswordRequest } from '../api/authApi'
import { lookupCompany } from '../api/publicApi'

function Shell({ title, children }) { return <div className="public-page min-h-screen bg-[#f4f8fd]"><Header /><main className="mx-auto max-w-3xl px-5 py-10"><h1 className="mb-6 text-3xl font-extrabold text-[#123a8b]">{title}</h1>{children}</main><Footer /></div> }
const fieldClass = 'mt-2 w-full rounded-md border border-[#d8e3f0] px-3 py-3 text-sm'
const actionClass = 'rounded-md bg-[#0757c9] px-5 py-3 text-sm font-bold text-white'
export function ForgotPasswordPage(){const[message,setMessage]=useState('');async function submit(event){event.preventDefault();try{const result=await forgotPasswordRequest(new FormData(event.currentTarget).get('email'));setMessage(result.resetToken?`Token development: ${result.resetToken}`:'Nếu email tồn tại, hướng dẫn đặt lại mật khẩu đã được gửi.')}catch(error){setMessage(error.response?.data?.error?.message||'Không thể gửi yêu cầu.')}}return <Shell title="Quên mật khẩu"><form className="space-y-4 rounded-xl border bg-white p-6" onSubmit={submit}><label className="block text-sm font-semibold">Email<input className={fieldClass} type="email" name="email" required/></label><button className={actionClass}>Gửi yêu cầu</button>{message&&<p role="status" className="text-sm">{message}</p>}</form></Shell>}
export function ResetPasswordPage(){const[message,setMessage]=useState('');async function submit(event){event.preventDefault();const values=Object.fromEntries(new FormData(event.currentTarget));if(values.password!==values.confirmPassword){setMessage('Xác nhận mật khẩu không khớp.');return}try{await resetPasswordRequest(values.token,values.password);setMessage('Đặt lại mật khẩu thành công. Bạn có thể đăng nhập.')}catch(error){setMessage(error.response?.data?.error?.message||'Không thể đặt lại mật khẩu.')}}return <Shell title="Đặt lại mật khẩu"><form className="space-y-4 rounded-xl border bg-white p-6" onSubmit={submit}><label className="block text-sm font-semibold">Token<input className={fieldClass} name="token" required/></label><label className="block text-sm font-semibold">Mật khẩu mới<input className={fieldClass} type="password" name="password" minLength="8" required/></label><label className="block text-sm font-semibold">Xác nhận mật khẩu<input className={fieldClass} type="password" name="confirmPassword" minLength="8" required/></label><button className={actionClass}>Đặt lại mật khẩu</button>{message&&<p role="status" className="text-sm">{message}</p>}</form></Shell>}
export function CompanyRegisterPage() {
  const [message, setMessage] = useState(''); const [code, setCode] = useState('')
  async function submit(event){event.preventDefault();const form=event.currentTarget,values=Object.fromEntries(new FormData(form));try{const result=await registerCompanyRequest({fullName:values.fullName,email:values.email,password:values.password,phone:values.phone,companyName:values.companyName,taxCode:values.taxCode,companyEmail:values.companyEmail,companyPhone:values.companyPhone,address:values.address,industry:values.industry});setMessage(`Đã gửi hồ sơ. Mã tra cứu: ${result.companyId}`);setCode(String(result.companyId));form.reset()}catch(error){setMessage(error.response?.data?.error?.message||'Không thể gửi đăng ký.')}}
  return <Shell title="Đăng ký doanh nghiệp"><form className="grid gap-4 rounded-xl border bg-white p-6 sm:grid-cols-2" onSubmit={submit}>{[['companyName','Tên doanh nghiệp'],['taxCode','Mã số thuế'],['companyEmail','Email doanh nghiệp'],['companyPhone','Điện thoại doanh nghiệp'],['fullName','Người đại diện'],['email','Email đăng nhập'],['phone','Điện thoại người đại diện'],['industry','Lĩnh vực'],['address','Địa chỉ'],['password','Mật khẩu']].map(([name,label])=><label className="text-sm font-semibold" key={name}>{label}<input className={fieldClass} name={name} required={['companyName','taxCode','companyEmail','fullName','email','password'].includes(name)} type={name.toLowerCase().includes('email')?'email':name==='password'?'password':'text'} minLength={name==='password'?8:undefined}/></label>)}<button className={`${actionClass} sm:col-span-2`}>Gửi đăng ký</button>{message&&<p role="status" className="text-sm sm:col-span-2">{message}</p>}{code&&<Link className="text-sm text-[#0757c9] sm:col-span-2" to="/company/lookup">Tra cứu hồ sơ</Link>}</form></Shell>
}
export function CompanyLookupPage(){const[query,setQuery]=useState(''),[found,setFound]=useState(null),[message,setMessage]=useState('');async function submit(event){event.preventDefault();try{setFound(await lookupCompany(query));setMessage('')}catch(error){setFound(null);setMessage(error.response?.data?.error?.message||'Không thể tra cứu hồ sơ.')}}return <Shell title="Tra cứu hồ sơ doanh nghiệp"><form className="flex flex-wrap gap-3 rounded-xl border bg-white p-6" onSubmit={submit}><label className="min-w-0 flex-1 text-sm">Mã hồ sơ, mã số thuế hoặc email<input required className={fieldClass} value={query} onChange={event=>setQuery(event.target.value)}/></label><button className={`${actionClass} self-end`}>Tra cứu</button></form>{(found||message)&&<div className="mt-4 rounded-xl border bg-white p-6 text-sm">{found?<><b>{found.name}</b><p>Trạng thái: {found.status}</p>{found.rejection_reason&&<p>Lý do: {found.rejection_reason}</p>}</>:message}</div>}</Shell>}
