import { useCallback } from 'react'
import { Link } from 'react-router'
import { ArrowRight, BriefcaseBusiness, FileText, UsersRound, CalendarDays, GraduationCap, ClipboardCheck } from 'lucide-react'
import { getSession } from '../services/sessionService'
import useApiResource from '../hooks/useApiResource'
import { ResourceState } from '../components/ui/PageUI'
import * as student from '../api/studentApi'
import * as company from '../api/companyApi'
import * as lecturer from '../api/lecturerApi'
import * as admin from '../api/adminApi'
import { roleLabels } from '../utils/display'
const configs = {
  student: { intro: 'Theo dõi hồ sơ và chuẩn bị cho bước tiếp theo trong kỳ thực tập.', stats: [['applications','Hồ sơ ứng tuyển',ClipboardCheck],['interviews','Lịch phỏng vấn',CalendarDays]], links: [['profile','Hồ sơ & CV',FileText],['opportunities','Tìm cơ hội thực tập',BriefcaseBusiness],['diary','Ghi nhật ký công việc',FileText],['reports','Nộp báo cáo',GraduationCap]] },
  company: { intro: 'Quản lý tuyển dụng và đồng hành cùng sinh viên thực tập.', stats: [['jobs','Tin tuyển dụng',BriefcaseBusiness],['applications','Hồ sơ ứng viên',UsersRound]], links: [['jobs/create','Tạo tin tuyển dụng',BriefcaseBusiness],['applications','Xem hồ sơ ứng viên',UsersRound],['interviews','Lịch phỏng vấn',CalendarDays],['interns','Sinh viên thực tập',GraduationCap]] },
  lecturer: { intro: 'Nắm tiến độ sinh viên và xử lý những nội dung cần phản hồi.', stats: [['students','Sinh viên phụ trách',UsersRound],['internships','Hồ sơ thực tập',GraduationCap]], links: [['students','Sinh viên được phân công',UsersRound],['diaries','Nhận xét nhật ký',FileText],['reports','Duyệt báo cáo',ClipboardCheck],['evaluations','Đánh giá cuối kỳ',GraduationCap]] },
  admin: { intro: 'Điều phối kỳ thực tập, phê duyệt hồ sơ và theo dõi kết quả.', stats: [['users','Tài khoản',UsersRound],['companies','Doanh nghiệp',BriefcaseBusiness],['applications','Hồ sơ ứng tuyển',ClipboardCheck],['reportsPending','Báo cáo chờ duyệt',FileText]], links: [['internship-periods','Quản lý kỳ thực tập',CalendarDays],['companies','Phê duyệt doanh nghiệp',BriefcaseBusiness],['assignments','Phân công giảng viên',UsersRound],['reports','Báo cáo thống kê',FileText]] },
}
const loaders = {
  student: async () => { const [applications, interviews] = await Promise.all([student.getApplications(), student.getInterviews()]); return { applications: applications.length, interviews: interviews.length, tasks: [{ title: 'Kiểm tra hồ sơ ứng tuyển', body: 'Xem trạng thái xét duyệt và phản hồi từ doanh nghiệp.', path: 'applications' }, ...(interviews.some(x => x.student_response === 'pending') ? [{ title: 'Bạn có lịch phỏng vấn cần phản hồi', body: 'Kiểm tra thời gian và xác nhận với doanh nghiệp.', path: 'interviews' }] : []), { title: 'Chuẩn bị hồ sơ cá nhân', body: 'Kiểm tra thông tin và CV trước khi gửi hồ sơ.', path: 'profile' }] } },
  company: async () => { const [jobs, applications] = await Promise.all([company.getJobs(), company.getApplications()]); return { jobs: jobs.total, applications: applications.total, tasks: [{ title: 'Tiếp nhận hồ sơ ứng viên', body: 'Xem hồ sơ và phản hồi ứng viên đã được nhà trường xác nhận.', path: 'applications' }, { title: 'Kiểm tra tin tuyển dụng', body: 'Cập nhật nội dung, hạn tuyển và trạng thái xuất bản.', path: 'jobs' }] } },
  lecturer: async () => { const [students, internships] = await Promise.all([lecturer.getStudents(), lecturer.getInternships()]); return { students: students.length, internships: internships.length, tasks: [{ title: 'Theo dõi sinh viên được phân công', body: 'Kiểm tra nơi thực tập và tiến độ của sinh viên.', path: 'internships' }, { title: 'Phản hồi nhật ký và báo cáo', body: 'Giúp sinh viên điều chỉnh công việc và hoàn thiện báo cáo.', path: 'reports' }] } },
  admin: async () => { const data = await admin.dashboard(); return { ...data, tasks: [{ title: 'Doanh nghiệp chờ phê duyệt', body: `${data.companies?.pending || 0} doanh nghiệp đang chờ kiểm tra hồ sơ.`, path: 'companies' }, { title: 'Điều phối hồ sơ thực tập', body: 'Xác nhận ứng tuyển và kiểm tra phân công giảng viên.', path: 'applications' }, { title: 'Theo dõi báo cáo', body: `${data.reportsPending || 0} báo cáo đang chờ giảng viên duyệt.`, path: 'reports' }] } },
}
export default function DashboardPage() {
  const session = getSession(), role = session?.role || 'student', config = configs[role]
  const loader = useCallback(() => loaders[role](), [role]), resource = useApiResource(loader, {})
  return <section><div className="dashboard-page-heading"><div><p className="dashboard-eyebrow">KHÔNG GIAN {roleLabels[role].toUpperCase()}</p><h1>Chào bạn, {session?.name || session?.full_name || 'thành viên'}.</h1><p>{config.intro}</p></div><Link className="button button-secondary" to="/guide">Hướng dẫn <ArrowRight size={16} /></Link></div><ResourceState resource={resource}><div className="workspace-stats">{config.stats.map(([key,label,Icon]) => <article className="workspace-stat" key={key}><div><span>{label}</span><Icon size={20} /></div><strong>{typeof resource.data[key] === 'object' ? resource.data[key]?.total || 0 : resource.data[key] || 0}</strong></article>)}</div><div className="workspace-grid"><section className="workspace-panel"><p className="eyebrow">BƯỚC TIẾP THEO</p><h2>Công việc của bạn</h2>{resource.data.tasks?.map(task => <div className="workspace-task" key={task.path}><div><b>{task.title}</b><p>{task.body}</p></div><Link className="text-link shrink-0" to={`/${role}/${task.path}`}>Mở <ArrowRight size={15} /></Link></div>)}</section><section className="workspace-panel"><p className="eyebrow">THAO TÁC NHANH</p><h2>Đi đến chức năng</h2>{config.links.map(([path,label,Icon]) => <Link className="quick-link" to={`/${role}/${path}`} key={path}><Icon size={19} /><span>{label}</span><ArrowRight size={16} /></Link>)}</section></div></ResourceState></section>
}
