import { Link, useNavigate } from 'react-router'
import { INTERNSHIP_STATUSES } from '../constants/internshipStatuses'
import { getSession, logout } from '../services/mockAuth'
import { getAllApplications, getApplicationCompanyId } from '../services/applicationService'
import { getInterviews } from '../services/interviewService'
import { getRecords } from '../services/internshipRecordService'
import { getReports } from '../services/reportService'
import { getRegistrations, getJobs } from '../services/companyService'
import StatCard from '../components/dashboard/StatCard'

const quick = { student: [['/student/opportunities', 'Tìm cơ hội'], ['/student/applications', 'Xem hồ sơ']], company: [['/company/jobs', 'Tin tuyển dụng'], ['/company/applications', 'Hồ sơ ứng viên']], lecturer: [['/lecturer/students', 'Sinh viên phụ trách'], ['/lecturer/reports', 'Báo cáo']], admin: [['/admin/companies', 'Duyệt doanh nghiệp'], ['/admin/assignments', 'Phân công']] }
function DashboardPage() {
  const navigate = useNavigate(); const session = getSession(); const all = getAllApplications(); const interviews = getInterviews(); const records = getRecords(); const reports = getReports(); const applications = session.role === 'student' ? all.filter((item) => item.studentId === session.id) : session.role === 'company' ? all.filter((item) => getApplicationCompanyId(item) === session.id) : session.role === 'lecturer' ? all.filter((item) => records.some((record) => record.applicationId === item.id && record.lecturerId === session.id)) : all
  const mineInterviews = interviews.filter((item) => session.role === 'student' ? item.studentId === session.id : session.role === 'company' ? item.companyId === session.id : false)
  const mineRecords = records.filter((item) => session.role === 'student' ? item.studentId === session.id : session.role === 'company' ? item.companyId === session.id : session.role === 'lecturer' ? item.lecturerId === session.id : true)
  const stats = session.role === 'student' ? [['Hồ sơ ứng tuyển', applications.length], ['Lịch phỏng vấn', mineInterviews.length], ['Đang thực tập', mineRecords.filter((item) => item.status === 'Đang thực tập').length], ['Hoàn thành', applications.filter((item) => item.status === '15').length]] : session.role === 'company' ? [['Tin tuyển dụng', getJobs().filter((item) => item.companyId === session.id).length], ['Ứng viên', applications.length], ['Phỏng vấn', mineInterviews.length], ['Thực tập', mineRecords.length]] : session.role === 'lecturer' ? [['Sinh viên phụ trách', mineRecords.length], ['Đang thực tập', mineRecords.filter((item) => item.status === 'Đang thực tập').length], ['Báo cáo chờ duyệt', reports.filter((item) => mineRecords.some((record) => record.studentId === item.studentId) && item.status === 'Chờ giảng viên duyệt').length], ['Hoàn thành', applications.filter((item) => item.status === '15').length]] : [['Tổng hồ sơ', all.length], ['Doanh nghiệp chờ duyệt', getRegistrations().filter((item) => item.status === 'Chờ duyệt').length], ['Chờ phân công', records.filter((item) => item.status === 'Chờ nhà trường xác nhận').length], ['Hoàn thành', all.filter((item) => item.status === '15').length]]
  const current = applications.at(-1)
  return <section><div className="dashboard-page-heading"><div><p className="dashboard-eyebrow">TỔNG QUAN</p><h1>Xin chào, {session.name}</h1><p>Dữ liệu hoạt động hiện tại của bạn.</p></div><button className="dashboard-secondary-button" onClick={() => { logout(); navigate('/') }}>Đăng xuất</button></div><div className="dashboard-stats-grid">{stats.map(([label, value], index) => <StatCard key={label} label={label} value={value} note="Dữ liệu hiện tại" tone={['blue', 'green', 'orange', 'purple'][index]} />)}</div>{session.role === 'student' && <section className="dashboard-panel mt-6"><div className="dashboard-panel-heading"><h2>Hành trình thực tập</h2><Link to="/student/applications">Xem hồ sơ →</Link></div><div className="dashboard-timeline overflow-x-auto">{INTERNSHIP_STATUSES.map((status, index) => <div className={`dashboard-timeline-step ${current && Number(status.id) <= Number(current.status) ? 'done' : ''} ${current?.status === status.id ? 'current' : ''}`} key={status.id}>{index < INTERNSHIP_STATUSES.length - 1 && <span className="dashboard-timeline-connector" aria-hidden="true" />}<span className="dashboard-timeline-bullet">{status.id}</span><small>{status.label}</small></div>)}</div></section>}<section className="dashboard-panel mt-6"><div className="dashboard-panel-heading"><h2>Thao tác nhanh</h2></div><div className="dashboard-quick-actions">{quick[session.role].map(([href, label]) => <Link key={href} to={href}>{label}<span>→</span></Link>)}</div></section></section>
}
export default DashboardPage
