import { useCallback, useState } from 'react'
import { Link, useNavigate } from 'react-router'
import { ArrowRight, Search, MapPin, BriefcaseBusiness, FileCheck2, GraduationCap, CheckCircle2, Building2 } from 'lucide-react'
import { PublicLayout, ResourceState, EmptyState } from '../components/ui/PageUI'
import useApiResource from '../hooks/useApiResource'
import { listCompanies, listJobs } from '../api/publicApi'
import { formatDate, initials, salaryLabel, workModes } from '../utils/display'
export default function HomePage() {
  const [query, setQuery] = useState(''), navigate = useNavigate()
  const loader = useCallback(async () => { const [jobs, companies] = await Promise.all([listJobs({ limit: 6 }), listCompanies()]); return { jobs, companies } }, [])
  const resource = useApiResource(loader, { jobs: { items: [], total: 0 }, companies: [] })
  return <PublicLayout><section className="landing-hero"><div className="site-container landing-hero-grid"><div><span className="landing-badge"><span />Cùng bạn bắt đầu hành trình nghề nghiệp</span><h1>Thực tập đúng hướng.<br /><span>Tương lai rộng mở.</span></h1><p>Tìm cơ hội phù hợp và quản lý kỳ thực tập trong một không gian — từ hồ sơ đầu tiên đến kết quả cuối cùng.</p><form className="landing-search" onSubmit={e => { e.preventDefault(); navigate(`/opportunities?q=${encodeURIComponent(query.trim())}`) }}><Search size={20} /><input aria-label="Tìm vị trí hoặc doanh nghiệp" value={query} onChange={e => setQuery(e.target.value)} placeholder="Vị trí, kỹ năng hoặc doanh nghiệp…" /><button className="button button-primary">Tìm cơ hội <ArrowRight size={16} /></button></form><div className="landing-suggestions"><span>Gợi ý:</span>{['Frontend', 'Marketing', 'Kế toán'].map(x => <Link to={`/opportunities?q=${encodeURIComponent(x)}`} key={x}>{x}</Link>)}</div><div className="hero-meta"><span><CheckCircle2 size={16} /> Doanh nghiệp được phê duyệt</span><span><Shield /> Theo dõi xuyên suốt kỳ thực tập</span></div></div><div className="journey-visual"><div className="journey-heading"><span className="icon-tile"><GraduationCap size={26} /></span><div><p>HÀNH TRÌNH CỦA BẠN</p><h2>Từng bước đến mục tiêu</h2></div></div>{[['01', 'Chuẩn bị hồ sơ', 'CV và kỹ năng của bạn', FileCheck2], ['02', 'Kết nối cơ hội', 'Ứng tuyển và phỏng vấn', BriefcaseBusiness], ['03', 'Trải nghiệm thực tế', 'Nhật ký và báo cáo thực tập', Building2], ['04', 'Ghi nhận kết quả', 'Đánh giá và hoàn thành', GraduationCap]].map(([number, title, detail, Icon]) => <div className="journey-item" key={number}><span>{number}</span><div><h3>{title}</h3><p>{detail}</p></div><Icon size={21} /></div>)}<div className="journey-footer"><CheckCircle2 size={17} />Sinh viên · Doanh nghiệp · Nhà trường</div></div></div></section>
    <section className="site-container section-space"><div className="section-heading"><div><p className="eyebrow">BẮT ĐẦU TỪ MỘT CƠ HỘI</p><h2 className="section-title">Vị trí đang tuyển thực tập sinh</h2></div><Link className="text-link" to="/opportunities">Xem tất cả <ArrowRight size={16} /></Link></div><ResourceState resource={resource}>{resource.data.jobs.items.length ? <div className="jobs-grid">{resource.data.jobs.items.map(job => <article className="job-card" key={job.id}><div className="flex items-center gap-3"><span className="company-logo">{initials(job.company_name)}</span><div><span className="tag">{workModes[job.work_mode] || 'Thực tập'}</span><p className="text-sm text-muted mt-1">{job.company_name}</p></div></div><h3>{job.title}</h3><p className="job-location"><MapPin size={15} />{job.location || 'Chưa cập nhật'}</p><p className="job-salary">{salaryLabel(job.salary_min, job.salary_max)}</p><div className="job-footer"><span>Hạn {formatDate(job.deadline)}</span><Link className="text-link" to={`/opportunities?job=${job.id}`}>Chi tiết <ArrowRight size={15} /></Link></div></article>)}</div> : <EmptyState title="Chưa có vị trí tuyển dụng mới" description="Quay lại sau để xem cơ hội được doanh nghiệp công bố." />}</ResourceState></section>
    <section className="landing-role-section"><div className="site-container"><div className="section-heading"><div><p className="eyebrow">MỘT NỀN TẢNG, NHIỀU KẾT NỐI</p><h2 className="section-title">Không gian dành cho bạn</h2></div></div><div className="landing-role-grid">{[['Sinh viên', 'Chuẩn bị hồ sơ, tìm cơ hội và theo dõi kỳ thực tập của bạn.', '/guide?role=sinh-vien', GraduationCap], ['Doanh nghiệp', 'Đăng tin, tuyển chọn ứng viên và đồng hành cùng thực tập sinh.', '/guide?role=doanh-nghiep', Building2], ['Giảng viên & nhà trường', 'Điều phối, hướng dẫn và đánh giá trên cùng một quy trình.', '/guide?role=giang-vien', FileCheck2]].map(([title, body, to, Icon]) => <Link className="landing-role-card" to={to} key={title}><span className="icon-tile"><Icon size={24} /></span><h3>{title}</h3><p>{body}</p><span className="text-link">Khám phá chức năng <ArrowRight size={15} /></span></Link>)}</div></div></section>
    <section className="site-container section-space"><div className="section-heading"><div><p className="eyebrow">DOANH NGHIỆP ĐỒNG HÀNH</p><h2 className="section-title">Kết nối với môi trường thực tế</h2></div><Link className="text-link" to="/companies">Tất cả doanh nghiệp <ArrowRight size={16} /></Link></div><div className="partner-grid">{resource.data.companies.slice(0, 6).map(company => <Link to={`/companies?company=${company.id}`} key={company.id}><span className="company-logo">{initials(company.name)}</span><b>{company.name}</b><small>{company.industry || 'Đa lĩnh vực'}</small></Link>)}</div><div className="landing-cta"><div><p className="eyebrow">CHUẨN BỊ TỐT, BẮT ĐẦU TỰ TIN</p><h2>Bạn đã sẵn sàng cho kỳ thực tập?</h2><p>Đọc hướng dẫn để biết cần làm gì ở từng giai đoạn.</p></div><Link className="button button-primary" to="/guide">Xem hướng dẫn <ArrowRight size={16} /></Link></div></section>
  </PublicLayout>
}
function Shield() { return <FileCheck2 size={16} /> }
