import { Eye, EyeOff, GraduationCap, ArrowRight, ArrowLeft, CheckCircle2 } from 'lucide-react'
import { useState } from 'react'
import { Link, useNavigate, useSearchParams } from 'react-router'
import { login } from '../services/sessionService'
export default function LoginPage() {
  const navigate = useNavigate(), [params] = useSearchParams()
  const [email,setEmail] = useState(''), [password,setPassword] = useState(''), [show,setShow] = useState(false), [busy,setBusy] = useState(false), [error,setError] = useState('')
  async function submit(event) { event.preventDefault(); if (busy) return; setBusy(true); setError(''); try { const session = await login(email.trim(),password); const back = params.get('returnUrl'); navigate(back?.startsWith('/') && !back.startsWith('//') ? back : `/${session.role}/dashboard`,{replace:true}) } catch (err) { setError(err.response?.data?.error?.message || 'Không thể đăng nhập. Vui lòng kiểm tra email và mật khẩu.') } finally { setBusy(false) } }
  return <main className="auth-layout"><section className="auth-story"><Link className="brand" to="/"><span className="brand-mark"><GraduationCap size={23} /></span>InternConnect</Link><div><p className="eyebrow">MỖI KỲ THỰC TẬP, MỘT BƯỚC TIẾN</p><h2>Kết nối cơ hội.<br />Phát triển bản thân.</h2><p>Một không gian cho sinh viên, doanh nghiệp và nhà trường cùng đồng hành trong hành trình thực tập.</p><div className="auth-benefits">{['Theo dõi hồ sơ ứng tuyển rõ ràng','Quản lý công việc và báo cáo tập trung','Nhận phản hồi từ người hướng dẫn'].map(x => <span key={x}><CheckCircle2 size={19} />{x}</span>)}</div></div><small>Chuẩn bị tốt hôm nay. Tự tin bước vào nghề nghiệp.</small></section><section className="auth-form-wrap"><div className="auth-form"><Link className="back-link" to="/"><ArrowLeft size={16} />Về trang chủ</Link><p className="eyebrow mt-10">CHÀO MỪNG TRỞ LẠI</p><h1>Đăng nhập</h1><p className="muted mt-3">Tiếp tục hành trình thực tập của bạn.</p><form onSubmit={submit} className="mt-8"><label htmlFor="login-email">Email</label><input id="login-email" required autoComplete="username" type="email" placeholder="Nhập email tài khoản" value={email} onChange={e => setEmail(e.target.value)} disabled={busy} /><div className="flex items-center justify-between mt-6"><label htmlFor="login-password">Mật khẩu</label><Link className="text-link text-xs" to="/forgot-password">Quên mật khẩu?</Link></div><div className="password-field"><input id="login-password" required autoComplete="current-password" type={show ? 'text' : 'password'} placeholder="Nhập mật khẩu" value={password} onChange={e => setPassword(e.target.value)} disabled={busy} /><button className="icon-button" type="button" aria-label={show ? 'Ẩn mật khẩu' : 'Hiện mật khẩu'} aria-pressed={show} onClick={() => setShow(!show)}>{show ? <EyeOff size={18} /> : <Eye size={18} />}</button></div>{error && <p role="alert" className="mt-5">{error}</p>}<button disabled={busy} className="button button-primary w-full mt-7">{busy ? 'Đang đăng nhập…' : 'Đăng nhập'}<ArrowRight size={17} /></button></form><div className="auth-note">Sinh viên và giảng viên sử dụng tài khoản do nhà trường cấp. Nếu chưa có tài khoản, hãy liên hệ bộ phận phụ trách thực tập.</div><p className="text-sm muted mt-6">Bạn đại diện doanh nghiệp? <Link className="text-link" to="/company/register">Đăng ký tham gia</Link></p></div></section></main>
}
