import { Eye, EyeOff, LockKeyhole, Mail, ShieldCheck } from 'lucide-react'
import { useState } from 'react'
import { Link, useNavigate, useSearchParams } from 'react-router'
import { login } from '../services/sessionService'

export default function LoginPage() {
  const navigate = useNavigate(), [params] = useSearchParams()
  const [email,setEmail]=useState(''), [password,setPassword]=useState(''), [show,setShow]=useState(false), [busy,setBusy]=useState(false), [error,setError]=useState('')
  async function submit(event){event.preventDefault();setBusy(true);setError('');try{const session=await login(email.trim(),password);const back=params.get('returnUrl');navigate(back?.startsWith('/')&&!back.startsWith('//')?back:`/${session.role}/dashboard`)}catch(err){setError(err.response?.data?.error?.message||'Không thể đăng nhập. Vui lòng kiểm tra email và mật khẩu.')}finally{setBusy(false)}}
  return <main className="min-h-screen bg-[#f3f7fb] px-4 py-8"><div className="mx-auto grid max-w-5xl overflow-hidden rounded-2xl border border-[#dbe7f3] bg-white shadow-xl lg:grid-cols-2">
    <section className="hidden bg-[#0757c9] p-12 text-white lg:flex lg:flex-col lg:justify-between"><Link to="/" className="text-xl font-extrabold">INTERNCONNECT</Link><div><p className="text-sm font-bold text-blue-100">KẾT NỐI ĐÚNG CƠ HỘI</p><h1 className="mt-4 text-5xl font-extrabold leading-tight">Quản lý hành trình thực tập trong một nền tảng.</h1><p className="mt-5 leading-7 text-blue-100">Dành cho sinh viên, doanh nghiệp, giảng viên và nhà trường.</p></div><p className="flex items-center gap-2 text-sm text-blue-100"><ShieldCheck size={18}/> Xác thực và phân quyền theo vai trò</p></section>
    <section className="flex items-center justify-center p-7 sm:p-12"><form className="w-full max-w-md" onSubmit={submit}><Link to="/" className="text-lg font-extrabold text-[#0757c9] lg:hidden">INTERNCONNECT</Link><p className="mt-8 text-xs font-bold uppercase tracking-widest text-[#0a66c2]">Chào mừng trở lại</p><h1 className="mt-2 text-3xl font-extrabold text-[#172d50]">Đăng nhập tài khoản</h1><p className="mt-2 text-sm leading-6 text-[#7890ad]">Sử dụng tài khoản do nhà trường cấp hoặc tài khoản doanh nghiệp đã được phê duyệt.</p>
      <label className="mt-8 block text-sm font-bold text-[#2b4263]">Email<div className="mt-2 flex items-center rounded-lg border border-[#d8e3f0] px-3"><Mail size={17}/><input required autoComplete="email" type="email" className="min-w-0 flex-1 px-3 py-3 outline-none" value={email} onChange={e=>setEmail(e.target.value)}/></div></label>
      <label className="mt-4 block text-sm font-bold text-[#2b4263]">Mật khẩu<div className="mt-2 flex items-center rounded-lg border border-[#d8e3f0] px-3"><LockKeyhole size={17}/><input required autoComplete="current-password" type={show?'text':'password'} className="min-w-0 flex-1 px-3 py-3 outline-none" value={password} onChange={e=>setPassword(e.target.value)}/><button type="button" aria-label={show?'Ẩn mật khẩu':'Hiện mật khẩu'} onClick={()=>setShow(!show)}>{show?<EyeOff size={17}/>:<Eye size={17}/>}</button></div></label>
      <div className="mt-4 flex justify-between text-sm"><Link className="font-bold text-[#0757c9]" to="/company/register">Đăng ký doanh nghiệp</Link><Link className="font-bold text-[#0757c9]" to="/forgot-password">Quên mật khẩu?</Link></div>{error&&<p role="alert" className="mt-4 rounded-lg bg-red-50 px-3 py-2 text-sm font-semibold text-red-700">{error}</p>}<button disabled={busy} className="mt-6 w-full rounded-lg bg-[#34204f] py-3.5 font-bold text-white disabled:opacity-60">{busy?'Đang đăng nhập…':'Đăng nhập'}</button>
    </form></section>
  </div></main>
}
