import { useState } from 'react'
import { Link, useSearchParams } from 'react-router'
import Header from '../components/Header/Header'
import Footer from '../components/Footer/Footer'
import { getCompany, getRegistrations } from '../services/companyService'

function Shell({ title, description, children }) { return <><Header /><main className="public-page min-h-screen bg-[#f4f8fd]"><section className="public-info-hero px-5 py-12"><div className="mx-auto max-w-6xl"><h1 className="text-4xl font-extrabold text-[#123a8b]">{title}</h1><p className="mt-3 text-sm">{description}</p></div></section><div className="mx-auto max-w-6xl px-5 py-10">{children}</div></main><Footer /></> }
const box = 'rounded-xl border border-[#dce9f7] bg-white p-6'
const seed = [{ id: 'welcome', title: 'Quy trình thực tập tại InternConnect', category: 'Hướng dẫn', body: 'Sinh viên đăng ký, nhà trường xác nhận, doanh nghiệp tuyển chọn và giảng viên theo dõi quá trình thực tập.' }, { id: 'report', title: 'Hướng dẫn nộp báo cáo thực tập', category: 'Hướng dẫn', body: 'Sau khi bắt đầu thực tập, sinh viên có thể nộp từng phiên bản báo cáo và xem phản hồi của giảng viên.' }, { id: 'policy', title: 'Quy định xác nhận nơi thực tập', category: 'Quy định', body: 'Nhà trường xác nhận nơi thực tập và phân công giảng viên trước khi kỳ thực tập bắt đầu.' }]
function InformationPage() { const [query, setQuery] = useState(''); const [category, setCategory] = useState('Tất cả'); const [params, setParams] = useSearchParams(); const articles = [...seed, ...(() => { try { return JSON.parse(localStorage.getItem('internconnect_articles')) || [] } catch { return [] } })()]; const current = articles.find((item) => String(item.id) === params.get('article')); const filtered = articles.filter((item) => (category === 'Tất cả' || item.category === category) && `${item.title} ${item.body}`.toLowerCase().includes(query.toLowerCase())); return <Shell title="Thông tin" description="Thông báo, quy định và hướng dẫn thực tập."><div className="mb-5 grid gap-3 sm:grid-cols-[1fr_220px]"><label className="text-sm">Tìm bài viết<input className="mt-2 w-full rounded-md border p-3" value={query} onChange={(event) => setQuery(event.target.value)} /></label><label className="text-sm">Danh mục<select className="mt-2 w-full rounded-md border p-3" value={category} onChange={(event) => setCategory(event.target.value)}>{['Tất cả', 'Tin tức', 'Hướng dẫn', 'Quy định'].map((item) => <option key={item}>{item}</option>)}</select></label></div>{current ? <article className={box}><button className="mb-4 text-sm text-[#0757c9]" onClick={() => setParams({})}>← Danh sách</button><h2 className="text-2xl font-bold">{current.title}</h2><p className="mt-3 text-sm">{current.body}</p></article> : <div className="grid gap-4 sm:grid-cols-2">{filtered.map((item) => <article className={box} key={item.id}><small>{item.category}</small><h2 className="mt-2 font-bold">{item.title}</h2><p className="mt-2 text-sm">{item.body}</p><button className="mt-4 text-sm font-bold text-[#0757c9]" onClick={() => setParams({ article: item.id })}>Xem chi tiết →</button></article>)}</div>}<div className={`${box} mt-5`}><h2 className="font-bold">Tài liệu và hỗ trợ</h2><p className="mt-2 text-sm">Xem <Link className="text-[#0757c9]" to="/guide">hướng dẫn sử dụng</Link> hoặc <Link className="text-[#0757c9]" to="/contact">liên hệ hỗ trợ</Link>.</p></div></Shell> }
function CompaniesPage() { const [params, setParams] = useSearchParams(); const companies = [getCompany(), ...getRegistrations().filter((item) => item.status === 'Đã duyệt')]; const selected = companies.find((item) => String(item.id) === params.get('company')); return <Shell title="Doanh nghiệp đối tác" description="Tìm hiểu doanh nghiệp đã được nhà trường phê duyệt."><div className="mb-6 flex flex-wrap gap-3"><Link className="rounded-md bg-[#0757c9] px-4 py-3 text-sm font-bold text-white" to="/company/register">Đăng ký doanh nghiệp</Link><Link className="rounded-md border px-4 py-3 text-sm" to="/company/lookup">Tra cứu hồ sơ</Link></div>{selected ? <article className={box}><button className="text-sm text-[#0757c9]" onClick={() => setParams({})}>← Danh sách</button><h2 className="mt-3 text-xl font-bold">{selected.name}</h2><p className="mt-2 text-sm">{selected.industry} · {selected.address}</p><p className="mt-2 text-sm">{selected.description}</p></article> : <div className="grid gap-4 sm:grid-cols-2">{companies.map((item) => <article className={box} key={item.id}><h2 className="font-bold">{item.name}</h2><p className="text-sm">{item.industry} · {item.address}</p><button className="mt-3 text-sm text-[#0757c9]" onClick={() => setParams({ company: item.id })}>Xem chi tiết →</button></article>)}</div>}<div className={`${box} mt-6`}><h2 className="font-bold">Quy trình tuyển dụng</h2><p className="mt-2 text-sm">Gửi đăng ký → nhà trường duyệt → tạo tin → xuất bản → xem hồ sơ và mời phỏng vấn.</p></div></Shell> }
function GuidePage() { return <Shell title="Hướng dẫn sử dụng" description="Các bước thực tập theo từng vai trò."><div className="grid gap-4 md:grid-cols-3">{[['Sinh viên', 'Tạo hồ sơ, ứng tuyển, xác nhận lịch và đề nghị, nộp nhật ký và báo cáo.'], ['Doanh nghiệp', 'Đăng ký, chờ duyệt, xuất bản tin, phỏng vấn và đánh giá.'], ['Nhà trường', 'Xác nhận điều kiện, phân công giảng viên và ký hoàn thành.']].map(([title, body]) => <article className={box} key={title}><h2 className="font-bold">{title}</h2><p className="mt-2 text-sm">{body}</p></article>)}</div></Shell> }
function ContactPage() { return <Shell title="Liên hệ" description="Hỗ trợ sử dụng InternConnect."><div className={box}><p className="text-sm">Email: <a className="text-[#0757c9]" href="mailto:support@internconnect.vn">support@internconnect.vn</a></p><p className="mt-2 text-sm">Vui lòng mô tả rõ tài khoản và vấn đề cần hỗ trợ trong email.</p></div></Shell> }
function PublicInfoPage({ type }) { if (type === 'companies') return <CompaniesPage />; if (type === 'guide') return <GuidePage />; if (type === 'contact') return <ContactPage />; return <InformationPage /> }
export default PublicInfoPage
