import { useCallback, useState } from 'react'
import { Link, useParams, useSearchParams } from 'react-router'
import { ArrowRight, BookOpen, Building2, CalendarDays, CheckCircle2, ChevronDown, FileText, Mail, MapPin, Search, ShieldCheck } from 'lucide-react'
import useApiResource from '../hooks/useApiResource'
import { listCompanies } from '../api/publicApi'
import { publicContent } from '../api/contentApi'
import { PublicLayout, PageHero, ResourceState, EmptyState, BackLink } from '../components/ui/PageUI'
import { foldText, formatDate, initials } from '../utils/display'

const categories = ['Tất cả', 'Thông báo', 'Hướng dẫn', 'Quy định']
function categoryOf(article) {
  const title = foldText(article.title)
  if (title.includes('huong dan')) return 'Hướng dẫn'
  if (title.includes('quy dinh') || title.includes('quy che')) return 'Quy định'
  return 'Thông báo'
}

function InformationPage() {
  const loader = useCallback(() => publicContent(), [])
  const resource = useApiResource(loader, [])
  const [params, setParams] = useSearchParams()
  const query = params.get('q') || '', category = params.get('category') || 'Tất cả'
  const selected = resource.data.find(x => String(x.id) === params.get('article'))
  const filtered = resource.data.filter(x => (category === 'Tất cả' || categoryOf(x) === category) && foldText(`${x.title} ${x.body}`).includes(foldText(query)))
  function update(key, value) { const next = new URLSearchParams(params); if (value) next.set(key, value); else next.delete(key); next.delete('article'); setParams(next, { replace: true }) }
  return <PublicLayout><PageHero eyebrow="TRUNG TÂM THÔNG TIN" title="Thông tin để bạn sẵn sàng." description="Theo dõi thông báo, tìm hiểu quy định và chuẩn bị cho từng bước trong kỳ thực tập."><div className="hero-meta"><span><ShieldCheck size={16} /> Nội dung từ nhà trường</span><span><BookOpen size={16} /> Hướng dẫn theo từng vai trò</span></div></PageHero>
    <div className="site-container section-space information-layout"><section className="min-w-0">
      {params.get('article') ? <ResourceState resource={resource}>{selected ? <article className="article-detail"><BackLink to="/information">Tất cả thông tin</BackLink><span className="tag mt-6">{categoryOf(selected)}</span><h2>{selected.title}</h2><div className="article-meta"><CalendarDays size={16} />{formatDate(selected.published_at)}<span>· Nhà trường</span></div><div className="article-body">{selected.body.split(/\n\s*\n/).map((paragraph, index) => <p key={index}>{paragraph}</p>)}</div><div className="article-help">Cần giải thích thêm về nội dung này? <Link to="/contact">Liên hệ hỗ trợ <ArrowRight size={14} /></Link></div></article> : <EmptyState title="Không tìm thấy bài viết" description="Bài viết có thể đã được gỡ hoặc đường dẫn không còn hợp lệ." to="/information" action="Xem tất cả thông tin" />}</ResourceState> : <>
        <div className="content-toolbar"><div className="search-field"><Search size={19} /><input aria-label="Tìm thông báo hoặc tài liệu" placeholder="Tìm thông báo, quy định, hướng dẫn…" value={query} onChange={event => update('q', event.target.value)} />{query && <button aria-label="Xóa tìm kiếm" onClick={() => update('q', '')}>×</button>}</div></div>
        <div className="filter-tabs" aria-label="Lọc theo loại nội dung">{categories.map(x => <button className={category === x ? 'selected' : ''} aria-pressed={category === x} onClick={() => update('category', x)} key={x}>{x}</button>)}</div>
        <div className="section-heading"><h2>{category === 'Tất cả' ? 'Cập nhật mới nhất' : category}</h2>{!resource.loading && <span>{filtered.length} bài viết</span>}</div>
        <ResourceState resource={resource} emptyTitle="Chưa có thông tin được công bố" emptyDescription="Thông báo và tài liệu từ nhà trường sẽ xuất hiện tại đây.">{filtered.length === 0 ? <EmptyState title="Không tìm thấy nội dung phù hợp" description="Thử từ khóa ngắn hơn hoặc chọn một loại nội dung khác." /> : <div className="article-list">{filtered.map((article, index) => <Link className={`article-card ${index === 0 && !query && category === 'Tất cả' ? 'featured' : ''}`} to={`?article=${article.id}`} key={article.id}><div className="article-symbol"><FileText size={24} /></div><div className="min-w-0"><div className="article-meta"><span className="tag">{categoryOf(article)}</span><span>{formatDate(article.published_at)}</span></div><h3>{article.title}</h3><p>{article.body}</p><span className="text-link">Đọc bài viết <ArrowRight size={15} /></span></div></Link>)}</div>}</ResourceState>
      </>}
    <section className="learning-section"><div className="section-heading"><div><p className="eyebrow">CẨM NANG NỀN TẢNG</p><h2>Chuẩn bị cho kỳ thực tập</h2></div></div><div className="learning-grid">{[['Hồ sơ & CV', 'Chuẩn bị thông tin cá nhân, kỹ năng và CV trước khi ứng tuyển.', '/guide?role=sinh-vien', FileText], ['Quy trình ứng tuyển', 'Hiểu vai trò của nhà trường và doanh nghiệp trong từng giai đoạn.', '/guide?role=sinh-vien', BookOpen], ['Nhật ký & báo cáo', 'Theo dõi công việc, gửi báo cáo và nhận phản hồi từ giảng viên.', '/guide?role=giang-vien', CalendarDays]].map(([title, body, to, Icon]) => <Link className="learning-card" key={title} to={to}><Icon size={22}/><h3>{title}</h3><p>{body}</p><span className="text-link">Đọc hướng dẫn <ArrowRight size={14}/></span></Link>)}</div></section>    </section><aside className="information-aside"><div className="help-card"><span className="icon-tile"><BookOpen size={23} /></span><h2>Mới bắt đầu thực tập?</h2><p>Hướng dẫn từng bước, từ hoàn thiện hồ sơ đến nhận kết quả cuối kỳ.</p><Link className="button button-primary" to="/guide">Xem hướng dẫn <ArrowRight size={16} /></Link></div><div className="surface aside-links"><h2>Truy cập nhanh</h2>{[['/student/profile', 'Chuẩn bị hồ sơ & CV'], ['/opportunities', 'Tìm cơ hội thực tập'], ['/student/applications', 'Theo dõi ứng tuyển'], ['/student/reports', 'Nộp báo cáo thực tập']].map(([to, label]) => <Link to={to} key={to}>{label}<ArrowRight size={15} /></Link>)}</div><div className="aside-note"><ShieldCheck size={20} /><p>Kiểm tra thông báo thường xuyên để không bỏ lỡ hướng dẫn và thay đổi từ nhà trường.</p></div></aside></div>
  </PublicLayout>
}

const guides = {
  'sinh-vien': { role: 'Sinh viên', icon: BookOpen, intro: 'Tìm cơ hội phù hợp và theo dõi hành trình thực tập của bạn.', steps: [['Chuẩn bị hồ sơ', 'Cập nhật thông tin cá nhân, kỹ năng và tải CV. Đặt CV mặc định trước khi ứng tuyển.', '/student/profile'], ['Tìm và ứng tuyển', 'Chọn vị trí phù hợp, CV và kỳ thực tập. Theo dõi hồ sơ sau khi gửi.', '/student/opportunities'], ['Phỏng vấn và nhận đề nghị', 'Xác nhận lịch phỏng vấn, kiểm tra kết quả và phản hồi đề nghị thực tập.', '/student/interviews'], ['Nhật ký và báo cáo', 'Sau khi thực tập bắt đầu, ghi nhật ký công việc và nộp báo cáo theo yêu cầu.', '/student/reports']] },
  'doanh-nghiep': { role: 'Doanh nghiệp', icon: Building2, intro: 'Tiếp cận ứng viên và đồng hành cùng sinh viên trong kỳ thực tập.', steps: [['Đăng ký và xét duyệt', 'Gửi hồ sơ doanh nghiệp và lưu mã tra cứu. Đăng nhập sau khi được nhà trường phê duyệt.', '/company/register'], ['Đăng tin tuyển dụng', 'Mô tả rõ công việc, yêu cầu, quyền lợi và hạn ứng tuyển trước khi xuất bản.', '/company/jobs'], ['Tuyển chọn ứng viên', 'Tiếp nhận hồ sơ, gửi lịch phỏng vấn và phản hồi kết quả cho sinh viên.', '/company/applications'], ['Theo dõi và đánh giá', 'Theo dõi sinh viên thực tập và gửi đánh giá khi kỳ thực tập đến giai đoạn đánh giá.', '/company/interns']] },
  'giang-vien': { role: 'Giảng viên', icon: FileText, intro: 'Hướng dẫn sinh viên, theo dõi tiến độ và phản hồi báo cáo.', steps: [['Kiểm tra phân công', 'Xem danh sách sinh viên và kỳ thực tập được nhà trường phân công.', '/lecturer/students'], ['Theo dõi tiến độ', 'Kiểm tra nơi thực tập và tiến độ của từng sinh viên.', '/lecturer/internships'], ['Phản hồi công việc', 'Đọc nhật ký và nhận xét để sinh viên điều chỉnh công việc kịp thời.', '/lecturer/diaries'], ['Duyệt báo cáo', 'Đọc báo cáo, phê duyệt hoặc yêu cầu chỉnh sửa với phản hồi rõ ràng.', '/lecturer/reports']] },
  'nha-truong': { role: 'Nhà trường', icon: ShieldCheck, intro: 'Điều phối kỳ thực tập và quản lý hồ sơ theo từng giai đoạn.', steps: [['Quản lý kỳ thực tập', 'Tạo kỳ thực tập và mở thời gian đăng ký.', '/admin/internship-periods'], ['Duyệt doanh nghiệp và hồ sơ', 'Kiểm tra doanh nghiệp, xác nhận hồ sơ sinh viên và gửi cho doanh nghiệp.', '/admin/applications'], ['Phân công giảng viên', 'Phân công người hướng dẫn trước khi xác nhận nơi thực tập.', '/admin/assignments'], ['Theo dõi kết quả', 'Theo dõi báo cáo, đánh giá và xác nhận hoàn thành khi đủ điều kiện.', '/admin/reports']] },
}

function GuidePage() {
  const { guideId } = useParams()
  const [params] = useSearchParams()
  const key = guideId || params.get('role') || 'sinh-vien', guide = guides[key]
  return <PublicLayout><PageHero eyebrow="HƯỚNG DẪN SỬ DỤNG" title="Mỗi bước đều có hướng dẫn." description="Chọn vai trò của bạn để biết cần chuẩn bị gì và thực hiện thao tác ở đâu." /><div className="site-container section-space"><div className="role-selector">{Object.entries(guides).map(([id, item]) => { const Icon = item.icon; return <Link className={key === id ? 'selected' : ''} to={`/guide?role=${id}`} key={id}><Icon size={22} />{item.role}</Link> })}</div>{guide ? <div className="guide-layout"><div><p className="eyebrow">DÀNH CHO {guide.role.toUpperCase()}</p><h2 className="section-title">{guide.intro}</h2><p className="muted mt-4">Thực hiện lần lượt các bước. Quyền truy cập và thao tác phụ thuộc vào trạng thái hồ sơ của bạn.</p><Link className="button button-primary mt-6" to="/login">Vào không gian làm việc <ArrowRight size={16} /></Link></div><div className="guide-steps">{guide.steps.map(([title, body, to], index) => <article className="guide-step" key={title}><span>{String(index + 1).padStart(2, '0')}</span><div><h3>{title}</h3><p>{body}</p><Link className="text-link" to={to}>Mở chức năng <ArrowRight size={14} /></Link></div></article>)}</div></div> : <EmptyState title="Không tìm thấy hướng dẫn" to="/guide" action="Chọn vai trò" />}<FAQ /></div></PublicLayout>
}

function FAQ() {
  return <section className="faq-section"><div><p className="eyebrow">GIẢI ĐÁP NHANH</p><h2 className="section-title">Bạn đang cần trợ giúp?</h2></div><div>{[['Tôi chưa có tài khoản, phải làm gì?', 'Sinh viên và giảng viên liên hệ nhà trường để được cấp tài khoản. Doanh nghiệp có thể đăng ký tại trang Đăng ký doanh nghiệp.'], ['Vì sao tôi chưa thể ghi nhật ký?', 'Nhật ký được mở khi nhà trường xác nhận nơi thực tập, phân công giảng viên và cho bắt đầu kỳ thực tập.'], ['Tôi có thể nộp lại báo cáo không?', 'Bạn có thể gửi phiên bản mới khi giảng viên yêu cầu chỉnh sửa. Kiểm tra phản hồi trước khi nộp lại.']].map(([q, a]) => <details key={q}><summary>{q}<ChevronDown size={18} /></summary><p>{a}</p></details>)}</div></section>
}

function CompaniesPage() {
  const loader = useCallback(() => listCompanies(), [])
  const resource = useApiResource(loader, [])
  const [query, setQuery] = useState(''), [industry, setIndustry] = useState('')
  const [params] = useSearchParams()
  const selected = resource.data.find(x => String(x.id) === params.get('company'))
  const industries = [...new Set(resource.data.map(x => x.industry).filter(Boolean))]
  const filtered = resource.data.filter(x => (!industry || x.industry === industry) && foldText(`${x.name} ${x.industry || ''} ${x.address || ''}`).includes(foldText(query)))
  return <PublicLayout><PageHero eyebrow="DOANH NGHIỆP ĐỐI TÁC" title="Tìm nơi bắt đầu phù hợp." description="Khám phá doanh nghiệp đã được nhà trường phê duyệt và tìm hiểu môi trường thực tập."><Link className="button button-primary mt-6" to="/company/register">Đăng ký doanh nghiệp <ArrowRight size={16} /></Link></PageHero><div className="site-container section-space"><ResourceState resource={resource} emptyTitle="Chưa có doanh nghiệp được công bố">{selected ? <article className="surface company-detail"><BackLink to="/companies">Tất cả doanh nghiệp</BackLink><div className="company-detail-heading"><span className="company-logo large">{initials(selected.name)}</span><div><span className="tag"><CheckCircle2 size={13} />Đã được phê duyệt</span><h2>{selected.name}</h2><p>{selected.industry || 'Chưa cập nhật lĩnh vực'}</p></div></div><p className="article-body">{selected.description || 'Doanh nghiệp chưa cập nhật phần giới thiệu.'}</p><p className="article-meta"><MapPin size={17} />{selected.address || 'Chưa cập nhật địa chỉ'}</p>{/^https?:\/\//i.test(selected.website || '') && <a className="text-link" href={selected.website} target="_blank" rel="noreferrer">Website doanh nghiệp <ArrowRight size={16} /></a>}<Link className="button button-primary mt-6" to={`/opportunities?q=${encodeURIComponent(selected.name)}`}>Xem cơ hội tuyển dụng <ArrowRight size={16} /></Link></article> : <><div className="content-toolbar"><div className="search-field"><Search size={19} /><input aria-label="Tìm doanh nghiệp" placeholder="Tên doanh nghiệp, lĩnh vực, địa chỉ…" value={query} onChange={e => setQuery(e.target.value)} /></div><select aria-label="Lọc lĩnh vực" value={industry} onChange={e => setIndustry(e.target.value)}><option value="">Tất cả lĩnh vực</option>{industries.map(x => <option key={x}>{x}</option>)}</select></div><div className="section-heading"><h2>Doanh nghiệp đồng hành</h2><span>{filtered.length} doanh nghiệp</span></div>{filtered.length ? <div className="company-grid">{filtered.map(company => <Link className="company-card" to={`?company=${company.id}`} key={company.id}><span className="company-logo">{initials(company.name)}</span><span className="tag">{company.industry || 'Đa lĩnh vực'}</span><h3>{company.name}</h3><p><MapPin size={15} />{company.address || 'Chưa cập nhật địa chỉ'}</p><span className="text-link">Tìm hiểu doanh nghiệp <ArrowRight size={15} /></span></Link>)}</div> : <EmptyState title="Không tìm thấy doanh nghiệp" description="Thử từ khóa hoặc lĩnh vực khác." />}</>}</ResourceState></div></PublicLayout>
}

function ContactPage() {
  const [subject, setSubject] = useState(''), [message, setMessage] = useState('')
  return <PublicLayout><PageHero eyebrow="LIÊN HỆ & HỖ TRỢ" title="Chúng tôi ở đây để hỗ trợ." description="Chọn kênh phù hợp để được hướng dẫn về tài khoản, hồ sơ và quá trình thực tập." /><div className="site-container section-space contact-layout"><div><div className="surface contact-card"><span className="icon-tile"><Mail size={24} /></span><h2>Hỗ trợ nền tảng</h2><p>Gặp lỗi đăng nhập, thao tác hoặc cần hướng dẫn sử dụng? Gửi mô tả để bộ phận hỗ trợ kiểm tra.</p><a className="text-link" href="mailto:support@internconnect.vn">support@internconnect.vn <ArrowRight size={16} /></a></div><div className="surface contact-card"><span className="icon-tile"><Building2 size={24} /></span><h2>Vấn đề về kỳ thực tập</h2><p>Liên hệ giảng viên hướng dẫn hoặc bộ phận phụ trách thực tập của trường để xác nhận lịch, phân công và kết quả.</p><Link className="text-link" to="/student/internship">Xem hồ sơ thực tập <ArrowRight size={16} /></Link></div></div><form className="surface contact-form" onSubmit={e => { e.preventDefault(); window.location.href = `mailto:support@internconnect.vn?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(message)}` }}><h2>Mô tả vấn đề của bạn</h2><p className="muted">Biểu mẫu sẽ mở ứng dụng email trên thiết bị của bạn.</p><label>Chủ đề<input value={subject} onChange={e => setSubject(e.target.value)} placeholder="Ví dụ: Không thể cập nhật hồ sơ" required /></label><label>Nội dung<textarea value={message} onChange={e => setMessage(e.target.value)} placeholder="Nêu thao tác bạn đang thực hiện và thông báo lỗi nhận được. Không gửi mật khẩu." rows={7} required /></label><button className="button button-primary">Soạn email hỗ trợ <ArrowRight size={16} /></button></form></div></PublicLayout>
}

export default function PublicInfoPage({ type }) {
  if (type === 'information') return <InformationPage />
  if (type === 'companies') return <CompaniesPage />
  if (type === 'guide') return <GuidePage />
  return <ContactPage />
}
