import { useState } from 'react'
import { getSession } from '../../services/mockAuth'
import { getRecords } from '../../services/internshipRecordService'
import { getAllApplications } from '../../services/applicationService'
import { getReports, reviewReport } from '../../services/reportService'
import { getEvaluations, saveEvaluation } from '../../services/evaluationService'
import { users } from '../../services/dataSource'

const box = 'rounded-xl border border-[#dce9f7] bg-white p-5'
const button = 'rounded-md bg-[#0757c9] px-4 py-2.5 text-sm font-bold text-white disabled:bg-slate-300'
const mine = () => getRecords().filter((record) => record.lecturerId === getSession()?.id)
const student = (id) => users.find((item) => item.id === id)?.name || `Sinh viên #${id}`
function Shell({ title, children }) { return <section><div className="dashboard-page-heading"><div><p className="dashboard-eyebrow">GIẢNG VIÊN</p><h1>{title}</h1></div></div>{children}</section> }
function Rows({ records }) { return <div className="space-y-3">{records.length ? records.map((record) => <article className={box} key={record.id}><h2 className="font-bold">{student(record.studentId)} · {record.position}</h2><p className="text-sm text-[#6684a8]">{record.company} · {record.period} · {record.status}</p></article>) : <p>Chưa có sinh viên được phân công.</p>}</div> }
export function LecturerStudentsPage() { return <Shell title="Sinh viên được phân công"><Rows records={mine()} /></Shell> }
export function LecturerInternshipsPage() { return <Shell title="Theo dõi thực tập"><Rows records={mine()} /></Shell> }
export function LecturerDiariesPage() { const [notes, setNotes] = useState(() => { try { return JSON.parse(localStorage.getItem('internconnect_student_notes')) || [] } catch { return [] } }); function comment(note) { const feedback = window.prompt('Nhận xét cho nhật ký này:') || ''; if (!feedback.trim()) return; const next = notes.map((item) => item.id === note.id ? { ...item, feedback, lecturerId: getSession().id } : item); localStorage.setItem('internconnect_student_notes', JSON.stringify(next)); setNotes(next) } const ids = mine().map((item) => item.studentId); return <Shell title="Nhật ký thực tập"><div className="space-y-3">{notes.filter((item) => ids.includes(item.studentId)).map((note) => <article className={box} key={note.id}><p className="text-sm">{student(note.studentId)} · {note.date}</p><p>{note.text}</p>{note.feedback && <p className="text-sm">Nhận xét: {note.feedback}</p>}<button className={`${button} mt-3`} onClick={() => comment(note)}>Gửi nhận xét</button></article>)}</div></Shell> }
export function LecturerReportsPage() { const [reports, setReports] = useState(getReports()); const [message, setMessage] = useState(''); const ids = mine().map((item) => item.applicationId); function review(report, approved) { const feedback = approved ? 'Báo cáo đạt yêu cầu.' : window.prompt('Yêu cầu chỉnh sửa:') || ''; const response = reviewReport(report.id, approved, feedback); setReports(response.reports); setMessage(response.ok ? 'Đã cập nhật báo cáo.' : response.error) } return <Shell title="Báo cáo cần duyệt">{message && <p role="status" className="mb-3 text-sm">{message}</p>}<div className="space-y-3">{reports.filter((item) => ids.includes(item.applicationId)).map((report) => <article className={box} key={report.id}><h2 className="font-bold">{student(report.studentId)} · {report.name}</h2><p className="text-sm">Phiên bản {report.version} · {report.status}</p><p className="text-xs">Tệp minh họa: {report.name}</p>{report.status === 'Chờ giảng viên duyệt' && <div className="mt-3 flex gap-2"><button className={button} onClick={() => review(report, true)}>Phê duyệt</button><button className="rounded-md border px-4 py-2 text-sm" onClick={() => review(report, false)}>Yêu cầu sửa</button></div>}</article>)}</div></Shell> }
export function LecturerEvaluationsPage() { const [evaluations, setEvaluations] = useState(getEvaluations()); const [scores, setScores] = useState({}); const [message, setMessage] = useState(''); function save(record) { const response = saveEvaluation({ studentId: record.studentId, applicationId: record.applicationId, evaluatorRole: 'lecturer', score: scores[record.id] }); setEvaluations(response.evaluations); setMessage(response.ok ? 'Đã gửi và khóa đánh giá.' : response.error) } return <Shell title="Đánh giá cuối kỳ">{message && <p role="status">{message}</p>}<div className="space-y-3">{mine().filter((record) => getAllApplications().some((app) => app.id === record.applicationId && app.status === '13')).map((record) => { const locked = evaluations.some((item) => item.applicationId === record.applicationId && item.evaluatorRole === 'lecturer'); return <article className={box} key={record.id}><h2 className="font-bold">{student(record.studentId)}</h2><label className="mt-3 block text-sm">Điểm 0–10<input className="mt-2 block w-full rounded-md border p-3" type="number" min="0" max="10" disabled={locked} value={scores[record.id] ?? ''} onChange={(event) => setScores({ ...scores, [record.id]: event.target.value })} /></label><button className={`${button} mt-3`} disabled={locked || scores[record.id] === undefined} onClick={() => save(record)}>{locked ? 'Đã khóa' : 'Gửi đánh giá'}</button></article> })}</div></Shell> }
