import { validateDiaryDate } from '../domain/internshipDates.js'
import{db,transaction}from'../config/database.js';import{AppError}from'../utils/AppError.js';import*as fileStorage from'./fileStorageService.js';
async function record(userId,e=db){const[rows]=await e.execute(`SELECT ir.*,c.name company_name,j.title job_title,u.full_name lecturer_name FROM internship_records ir JOIN students s ON s.id=ir.student_id JOIN companies c ON c.id=ir.company_id JOIN jobs j ON j.id=ir.job_id LEFT JOIN lecturers l ON l.id=ir.lecturer_id LEFT JOIN users u ON u.id=l.user_id WHERE s.user_id=? ORDER BY ir.created_at DESC LIMIT 1`,[userId]);if(!rows[0])throw new AppError(404,'INTERNSHIP_NOT_FOUND','Chưa có hồ sơ thực tập');return rows[0]}
export const getRecord=record
export async function logs(userId){const r=await record(userId);const[rows]=await db.execute('SELECT * FROM internship_logs WHERE internship_record_id=? ORDER BY log_date DESC',[r.id]);return rows}
export async function createLog(userId,input){const r=await record(userId);validateDiaryDate(r,input.logDate);if(!['active','evaluating'].includes(r.status))throw new AppError(409,'INTERNSHIP_NOT_ACTIVE','Kỳ thực tập chưa hoạt động');const[result]=await db.execute(`INSERT INTO internship_logs(internship_record_id,log_date,title,content,work_hours,status) VALUES(?,?,?,?,?,'submitted')`,[r.id,input.logDate,input.title,input.content,input.workHours??null]);return{id:result.insertId,status:'submitted'}}
export async function updateLog(userId,id,input){const r=await record(userId);validateDiaryDate(r,input.logDate);if(!['active','evaluating'].includes(r.status))throw new AppError(409,'INTERNSHIP_NOT_ACTIVE','Internship is not active');const[result]=await db.execute(`UPDATE internship_logs SET log_date=?,title=?,content=?,work_hours=? WHERE id=? AND internship_record_id=? AND status IN ('draft','submitted')`,[input.logDate,input.title,input.content,input.workHours??null,id,r.id]);if(!result.affectedRows)throw new AppError(409,'DIARY_NOT_EDITABLE','Không tìm thấy hoặc nhật ký đã được nhận xét');return{id:Number(id)}}
export async function reports(userId){const r=await record(userId);const[rows]=await db.execute('SELECT * FROM reports WHERE internship_record_id=? ORDER BY report_type,version DESC',[r.id]);return rows}
export async function submitReport(userId,input){if(!['progress','final'].includes(input.reportType))throw new AppError(422,'INVALID_REPORT_TYPE','Loại báo cáo không hợp lệ');const r=await record(userId);return transaction(async c=>{const[records]=await c.execute('SELECT status FROM internship_records WHERE id=? FOR UPDATE',[r.id]);if(!['active','evaluating'].includes(records[0]?.status))throw new AppError(409,'INTERNSHIP_NOT_ACTIVE','Internship is not active');const[latest]=await c.execute('SELECT id,version,status FROM reports WHERE internship_record_id=? AND report_type=? ORDER BY version DESC LIMIT 1 FOR UPDATE',[r.id,input.reportType]);if(latest[0]&&!['revision_required'].includes(latest[0].status))throw new AppError(409,'REPORT_VERSION_NOT_ALLOWED','Chỉ nộp phiên bản mới khi được yêu cầu chỉnh sửa');const version=(latest[0]?.version||0)+1;const[result]=await c.execute(`INSERT INTO reports(internship_record_id,report_type,version,file_path,file_name,mime_type,file_size,status,submitted_at) VALUES(?,?,?,?,?,?,?,'submitted',NOW())`,[r.id,input.reportType,version,input.path,input.originalName,input.mimeType,input.size]);return{id:result.insertId,version,status:'submitted'}})}
export async function removeUploaded(path){await fileStorage.remove(path)}
