import{db,transaction}from'../config/database.js';import{AppError}from'../utils/AppError.js';import{pageResult,pagination,sortClause}from'../utils/pagination.js';
async function lecturer(userId,e=db){const[rows]=await e.execute('SELECT id FROM lecturers WHERE user_id=?',[userId]);if(!rows[0])throw new AppError(403,'LECTURER_PROFILE_NOT_FOUND','Không tìm thấy hồ sơ giảng viên');return rows[0]}
export async function students(userId){const l=await lecturer(userId);const[rows]=await db.execute(`SELECT s.id,s.student_code,u.full_name,u.email,la.internship_period_id,ip.name period_name FROM lecturer_assignments la JOIN students s ON s.id=la.student_id JOIN users u ON u.id=s.user_id JOIN internship_periods ip ON ip.id=la.internship_period_id WHERE la.lecturer_id=? ORDER BY u.full_name`,[l.id]);return rows}
export async function internships(userId){const l=await lecturer(userId);const[rows]=await db.execute(`SELECT ir.*,u.full_name student_name,c.name company_name,j.title job_title FROM internship_records ir JOIN students s ON s.id=ir.student_id JOIN users u ON u.id=s.user_id JOIN companies c ON c.id=ir.company_id JOIN jobs j ON j.id=ir.job_id WHERE ir.lecturer_id=?`,[l.id]);return rows}
export async function diaries(userId){const l=await lecturer(userId);const[rows]=await db.execute(`SELECT il.*,u.full_name student_name FROM internship_logs il JOIN internship_records ir ON ir.id=il.internship_record_id JOIN students s ON s.id=ir.student_id JOIN users u ON u.id=s.user_id WHERE ir.lecturer_id=? ORDER BY il.log_date DESC`,[l.id]);return rows}
export async function feedback(userId,id,text){const l=await lecturer(userId);const[result]=await db.execute(`UPDATE internship_logs il JOIN internship_records ir ON ir.id=il.internship_record_id SET il.lecturer_feedback=?,il.reviewed_by=?,il.reviewed_at=NOW(),il.status='reviewed' WHERE il.id=? AND ir.lecturer_id=?`,[text,userId,id,l.id]);if(!result.affectedRows)throw new AppError(404,'DIARY_NOT_ASSIGNED','Không tìm thấy nhật ký thuộc sinh viên được phân công');return{id:Number(id),status:'reviewed'}}
export async function reports(userId){const l=await lecturer(userId);const[rows]=await db.execute(`SELECT r.*,u.full_name student_name FROM reports r JOIN internship_records ir ON ir.id=r.internship_record_id JOIN students s ON s.id=ir.student_id JOIN users u ON u.id=s.user_id WHERE ir.lecturer_id=? ORDER BY r.created_at DESC`,[l.id]);return rows}
export async function criteria(){const[rows]=await db.execute(`SELECT id,name,description,max_score,weight FROM evaluation_criteria WHERE evaluator_type='lecturer' AND active=TRUE ORDER BY id`);return rows}
export async function evaluations(userId){const l=await lecturer(userId);const[rows]=await db.execute(`SELECT e.*,u.full_name student_name FROM evaluations e JOIN internship_records ir ON ir.id=e.internship_record_id JOIN students s ON s.id=ir.student_id JOIN users u ON u.id=s.user_id WHERE ir.lecturer_id=? ORDER BY e.submitted_at DESC`,[l.id]);return rows}
export async function reviewReport(userId,id,input){return transaction(async c=>{const l=await lecturer(userId,c);const[rows]=await c.execute(`SELECT r.*,s.user_id student_user_id FROM reports r JOIN internship_records ir ON ir.id=r.internship_record_id JOIN students s ON s.id=ir.student_id WHERE r.id=? AND ir.lecturer_id=? FOR UPDATE`,[id,l.id]);const report=rows[0];if(!report)throw new AppError(404,'REPORT_NOT_ASSIGNED','Không tìm thấy báo cáo được phân công');if(report.status!=='submitted')throw new AppError(409,'REPORT_ALREADY_REVIEWED','Báo cáo không ở trạng thái chờ duyệt');await c.execute('INSERT INTO report_reviews(report_id,lecturer_id,decision,feedback) VALUES(?,?,?,?)',[id,l.id,input.decision,input.feedback||null]);await c.execute('UPDATE reports SET status=? WHERE id=?',[input.decision,id]);await c.execute(`INSERT INTO notifications(recipient_user_id,type,title,message,entity_type,entity_id) VALUES(?,'report_review','Kết quả duyệt báo cáo',?,'report',?)`,[report.student_user_id,input.decision==='approved'?'Báo cáo đã được duyệt.':'Báo cáo cần chỉnh sửa.',id]);return{id:Number(id),status:input.decision}})}
export async function evaluate(userId,recordId,input){return transaction(async c=>{const l=await lecturer(userId,c);const[records]=await c.execute(`SELECT id FROM internship_records WHERE id=? AND lecturer_id=? AND status='evaluating' FOR UPDATE`,[recordId,l.id]);if(!records.length)throw new AppError(404,'INTERNSHIP_NOT_ASSIGNED','Không tìm thấy kỳ thực tập được phân công');const[existing]=await c.execute(`SELECT id FROM evaluations WHERE internship_record_id=? AND evaluator_role='lecturer'`,[recordId]);if(existing.length)throw new AppError(409,'EVALUATION_LOCKED','Đánh giá đã gửi và không thể sửa');const ids=input.details.map(x=>x.criteriaId);const[criteria]=await c.query(`SELECT id,max_score,weight FROM evaluation_criteria WHERE evaluator_type='lecturer' AND active=TRUE AND id IN (?)`,[ids]);if(criteria.length!==new Set(ids).size)throw new AppError(422,'INVALID_EVALUATION_CRITERIA','Tiêu chí đánh giá không hợp lệ');const map=new Map(criteria.map(x=>[Number(x.id),x]));let weighted=0,totalWeight=0;for(const d of input.details){const rule=map.get(Number(d.criteriaId));if(d.score<0||d.score>rule.max_score)throw new AppError(422,'INVALID_EVALUATION_SCORE','Điểm vượt quá giới hạn tiêu chí');weighted+=(d.score/rule.max_score)*10*rule.weight;totalWeight+=rule.weight}const total=weighted/totalWeight;const[result]=await c.execute(`INSERT INTO evaluations(internship_record_id,evaluator_user_id,evaluator_role,total_score,comment) VALUES(?,?,'lecturer',?,?)`,[recordId,userId,total,input.comment||null]);for(const d of input.details)await c.execute('INSERT INTO evaluation_details(evaluation_id,criteria_id,score,comment) VALUES(?,?,?,?)',[result.insertId,d.criteriaId,d.score,d.comment||null]);return{id:result.insertId,totalScore:total}})}

export async function paginatedReports(userId, query = {}) {
  const assigned = await lecturer(userId), page = pagination(query), search = `%${query.search || ''}%`, params = [assigned.id,search]
  let where = 'WHERE ir.lecturer_id=? AND u.full_name LIKE ?'
  if (query.status) { where += ' AND r.status=?'; params.push(query.status) }
  const joins = 'FROM reports r JOIN internship_records ir ON ir.id=r.internship_record_id JOIN students s ON s.id=ir.student_id JOIN users u ON u.id=s.user_id'
  const [[items],[counts]] = await Promise.all([
    db.execute(`SELECT r.*,u.full_name student_name ${joins} ${where} ORDER BY ${sortClause(query.sort,{submitted:'r.submitted_at',student:'u.full_name',status:'r.status'},'submitted')} LIMIT ? OFFSET ?`,[...params,page.limit,page.offset]),
    db.execute(`SELECT COUNT(*) total ${joins} ${where}`,params),
  ])
  return pageResult(items,counts[0].total,page)
}
