import { useState } from 'react'
import internships from '../../data/internships.json'
import statuses from '../../data/internshipStatuses.json'
import { applyForInternship, getApplications, getStudent, saveStudent } from '../../services/studentService'

const key = 'internconnect_student_notes'
function readNotes() { try { return JSON.parse(localStorage.getItem(key)) || [] } catch { return [] } }
function saveNotes(notes) { localStorage.setItem(key, JSON.stringify(notes)); return notes }

export function StudentProfilePage() {
  const [student, setStudent] = useState(getStudent()); const [saved, setSaved] = useState(false)
  function submit(e) { e.preventDefault(); saveStudent(student); setSaved(true) }
  return <Page title="Hồ sơ cá nhân & CV" description="Quản lý thông tin dùng trong quá trình ứng tuyển."><form onSubmit={submit} className="rounded-xl border border-[#e1eaf5] bg-white p-6"><div className="grid gap-4 md:grid-cols-2">{[['fullName','Họ và tên'],['email','Email'],['phone','Số điện thoại'],['major','Chuyên ngành'],['className','Lớp']].map(([field,label]) => <label className="text-sm font-semibold text-[#2b4263]" key={field}>{label}<input value={student[field]} onChange={(e) => setStudent({ ...student, [field]: e.target.value })} className="mt-2 w-full rounded-md border border-[#d8e3f0] px-3 py-2.5 font-normal" /></label>)}</div><label className="mt-4 block text-sm font-semibold text-[#2b4263]">Kỹ năng<input value={student.skills.join(', ')} onChange={(e) => setStudent({ ...student, skills: e.target.value.split(',').map((x) => x.trim()).filter(Boolean) })} className="mt-2 w-full rounded-md border border-[#d8e3f0] px-3 py-2.5 font-normal" /></label><div className="mt-5 rounded-lg bg-[#edf4ff] p-4 text-sm text-[#4774b3]"><b>CV mặc định:</b> {student.cv.name}<br /><span className="text-xs">Hỗ trợ PDF/DOCX sẽ được nối storage backend ở giai đoạn sau.</span></div>{saved && <p className="mt-4 text-sm font-semibold text-green-600">Đã lưu hồ sơ.</p>}<button className="mt-5 rounded-md bg-[#0757c9] px-5 py-3 text-sm font-bold text-white" type="submit">Lưu thay đổi</button></form></Page>
}

export function StudentOpportunitiesPage() {
  const [query, setQuery] = useState(''); const [applications, setApplications] = useState(getApplications()); const [message, setMessage] = useState('')
  const items = internships.filter((item) => `${item.company} ${item.position} ${item.tags.join(' ')}`.toLowerCase().includes(query.toLowerCase())); const applied = new Set(applications.map((x) => x.internshipId))
  function apply(id) { setApplications(applyForInternship(id)); setMessage('Đã gửi hồ sơ ứng tuyển.') }
  return <Page title="Cơ hội thực tập" description="Tìm kiếm và ứng tuyển các vị trí phù hợp."><input className="mb-5 w-full rounded-lg border border-[#d8e3f0] bg-white px-4 py-3 text-sm" placeholder="Tìm công ty, vị trí hoặc kỹ năng..." value={query} onChange={(e) => setQuery(e.target.value)} />{message && <p className="mb-4 text-sm font-semibold text-green-600">{message}</p>}<div className="grid gap-4 md:grid-cols-2">{items.map((item) => <article className="rounded-xl border border-[#e1eaf5] bg-white p-5" key={item.id}><p className="text-xs text-[#7890ad]">{item.company} · {item.location}</p><h2 className="mt-2 font-bold text-[#172d50]">{item.position}</h2><div className="mt-3 flex flex-wrap gap-2">{item.tags.map((tag) => <span className="rounded-full bg-[#edf4ff] px-2 py-1 text-xs text-[#4774b3]" key={tag}>{tag}</span>)}</div><button type="button" onClick={() => apply(item.id)} disabled={applied.has(item.id)} className="mt-5 rounded-md bg-[#0757c9] px-4 py-2 text-sm font-bold text-white disabled:bg-slate-300">{applied.has(item.id) ? 'Đã ứng tuyển' : 'Ứng tuyển ngay'}</button></article>)}</div></Page>
}

export function StudentApplicationsPage() { const apps = getApplications(); return <Page title="Quản lý ứng tuyển" description="Theo dõi toàn bộ hồ sơ và lịch sử xử lý."><div className="space-y-4">{apps.map((app) => { const item = internships.find((x) => x.id === app.internshipId); const current = statuses.findIndex((x) => x.id === app.status); return <article className="rounded-xl border border-[#e1eaf5] bg-white p-5" key={app.id}><h2 className="font-bold text-[#172d50]">{item?.position} · {item?.company}</h2><p className="mt-1 text-sm font-semibold text-[#0757c9]">{app.statusLabel}</p><div className="mt-4 flex flex-wrap gap-2">{statuses.map((status, index) => <span className={`rounded-md px-2 py-1 text-[11px] ${index <= current ? 'bg-[#dcecff] font-bold text-[#0757c9]' : 'bg-slate-100 text-slate-400'}`} key={status.id}>{status.id}. {status.label}</span>)}</div></article>})}</div></Page> }

export function StudentInterviewsPage() { return <Page title="Lịch phỏng vấn" description="Theo dõi lịch phỏng vấn do doanh nghiệp gửi."><Empty title="Chưa có lịch phỏng vấn" text="Khi hồ sơ được mời phỏng vấn, lịch và trạng thái xác nhận sẽ hiển thị tại đây." /></Page> }
export function StudentInternshipPage() { return <Page title="Hồ sơ thực tập" description="Theo dõi doanh nghiệp, giảng viên hướng dẫn và tiến độ thực tập."><div className="rounded-xl border border-[#e1eaf5] bg-white p-6"><div className="flex items-center justify-between"><div><p className="text-sm text-[#7890ad]">Trạng thái hiện tại</p><h2 className="mt-1 text-xl font-bold text-[#172d50]">Chưa hình thành hồ sơ chính thức</h2></div><span className="rounded-full bg-amber-50 px-3 py-1 text-xs font-bold text-amber-700">Chờ xác nhận</span></div></div></Page> }
export function StudentDiaryPage() { const [notes, setNotes] = useState(readNotes()); const [text, setText] = useState(''); function add(e) { e.preventDefault(); if (!text.trim()) return; setNotes(saveNotes([{ id: Date.now(), date: new Date().toLocaleDateString('vi-VN'), text }, ...notes])); setText('') } return <Page title="Nhật ký thực tập" description="Ghi nhận công việc và nhận xét trong quá trình thực tập."><form onSubmit={add} className="rounded-xl border border-[#e1eaf5] bg-white p-5"><textarea className="min-h-32 w-full rounded-md border border-[#d8e3f0] p-3 text-sm" placeholder="Nhập nội dung nhật ký..." value={text} onChange={(e) => setText(e.target.value)} /><button className="mt-3 rounded-md bg-[#0757c9] px-4 py-2 text-sm font-bold text-white" type="submit">Lưu nhật ký</button></form><div className="mt-5 space-y-3">{notes.map((note) => <article className="rounded-lg border border-[#e1eaf5] bg-white p-4" key={note.id}><p className="text-xs font-bold text-[#7890ad]">{note.date}</p><p className="mt-2 text-sm text-[#2b4263]">{note.text}</p></article>)}</div></Page> }
export function StudentReportsPage() { return <Page title="Báo cáo thực tập" description="Nộp báo cáo tổng kết và theo dõi phản hồi từ giảng viên."><div className="rounded-xl border border-dashed border-[#b9cee8] bg-white p-8 text-center"><h2 className="font-bold text-[#172d50]">Chưa nộp báo cáo</h2><p className="mt-2 text-sm text-[#7890ad]">Bạn có thể tải lên báo cáo PDF/DOCX khi hồ sơ thực tập chính thức được tạo.</p><button className="mt-4 rounded-md bg-slate-300 px-4 py-2 text-sm font-bold text-white" type="button" disabled>Chọn file báo cáo</button></div></Page> }

function Page({ title, description, children }) { return <section><div className="mb-5"><h1 className="text-2xl font-extrabold text-[#172d50]">{title}</h1><p className="mt-1 text-sm text-[#7890ad]">{description}</p></div>{children}</section> }
function Empty({ title, text }) { return <div className="rounded-xl border border-dashed border-[#b9cee8] bg-white p-10 text-center"><h2 className="font-bold text-[#172d50]">{title}</h2><p className="mt-2 text-sm text-[#7890ad]">{text}</p></div> }
