import { useCallback, useState } from 'react'
import { Search, UsersRound, ArrowLeft, ArrowRight } from 'lucide-react'
import useApiResource from '../../hooks/useApiResource'
import { ResourceState } from '../../components/ui/PageUI'
import * as api from '../../api/adminApi'
import { roleLabels } from '../../utils/display'
const states = { active: 'Đang hoạt động', inactive: 'Ngừng hoạt động', locked: 'Đã khóa', pending: 'Chờ phê duyệt' }
export default function AdminUsersPage() {
  const [search,setSearch] = useState(''), [query,setQuery] = useState(''), [role,setRole] = useState(''), [status,setStatus] = useState(''), [page,setPage] = useState(1), [notice,setNotice] = useState(''), [busy,setBusy] = useState(null)
  const loader = useCallback(() => api.users({search:query,role,status,page,limit:20}), [query,role,status,page]), r = useApiResource(loader,{items:[]})
  async function change(id,value) { setBusy(id); try { await api.userStatus(id,value); setNotice('Đã cập nhật trạng thái tài khoản.'); r.reload() } catch (e) { setNotice(e.response?.data?.error?.message || 'Không thể cập nhật tài khoản.') } finally { setBusy(null) } }
  return <section><div className="dashboard-page-heading"><div><p className="eyebrow">QUẢN TRỊ NHÀ TRƯỜNG</p><h1>Quản lý tài khoản</h1><p>Tra cứu người dùng và quản lý trạng thái truy cập.</p></div><span className="dashboard-chip"><UsersRound size={14} className="inline mr-2" />Tài khoản hệ thống</span></div><form className="content-toolbar mb-5" onSubmit={e => { e.preventDefault(); setPage(1); setQuery(search) }}><div className="search-field"><Search size={18} /><input aria-label="Tìm người dùng" placeholder="Họ tên hoặc email…" value={search} onChange={e => setSearch(e.target.value)} /></div><select aria-label="Lọc vai trò" value={role} onChange={e => { setRole(e.target.value); setPage(1) }}><option value="">Tất cả vai trò</option>{Object.entries(roleLabels).map(([id,label]) => <option key={id} value={id}>{label}</option>)}</select><select aria-label="Lọc trạng thái" value={status} onChange={e => { setStatus(e.target.value); setPage(1) }}><option value="">Tất cả trạng thái</option>{Object.entries(states).map(([id,label]) => <option key={id} value={id}>{label}</option>)}</select><button className="button button-primary">Tìm kiếm</button></form>{notice && <p role="status" className="notice mb-5">{notice}</p>}<ResourceState resource={r} emptyTitle="Không tìm thấy tài khoản" emptyDescription="Kiểm tra từ khóa và điều kiện lọc."><div className="overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead><tr><th>Người dùng</th><th>Vai trò</th><th>Trạng thái</th><th>Thay đổi trạng thái</th></tr></thead><tbody>{r.data.items.map(x => <tr key={x.id}><td><b>{x.full_name}</b><small className="block muted mt-1">{x.email}</small></td><td>{roleLabels[x.role]}</td><td><span className={`status-badge ${x.status === 'active' ? 'success' : x.status === 'locked' ? 'danger' : 'muted'}`}>{states[x.status]}</span></td><td><select aria-label={`Trạng thái tài khoản ${x.email}`} value={x.status} disabled={busy === x.id} onChange={e => change(x.id,e.target.value)}>{Object.entries(states).map(([id,label]) => <option key={id} value={id}>{label}</option>)}</select></td></tr>)}</tbody></table></div></ResourceState><nav className="pagination" aria-label="Phân trang tài khoản"><button className="button button-secondary" disabled={page === 1 || r.loading} onClick={() => setPage(x => x - 1)}><ArrowLeft size={15} />Trước</button><span>Trang {page}</span><button className="button button-secondary" disabled={r.data.items.length < 20 || r.loading} onClick={() => setPage(x => x + 1)}>Sau<ArrowRight size={15} /></button></nav></section>
}
