import { useCallback } from 'react'
import { Link } from 'react-router'
import { ArrowRight, UsersRound, Building2, BriefcaseBusiness, ClipboardCheck, GraduationCap, FileText } from 'lucide-react'
import useApiResource from '../../hooks/useApiResource'
import { ResourceState } from '../../components/ui/PageUI'
import { dashboard } from '../../api/adminApi'
export default function AdminReportsPage() {
  const loader = useCallback(() => dashboard(), []), resource = useApiResource(loader,{})
  const data = resource.data
  const stats = [['Tổng tài khoản',data.users?.total,UsersRound],['Doanh nghiệp',data.companies?.total,Building2],['Tin đang tuyển',data.activeJobs,BriefcaseBusiness],['Hồ sơ ứng tuyển',data.applications,ClipboardCheck],['Đang thực tập',data.internships?.active,GraduationCap],['Báo cáo chờ duyệt',data.reportsPending,FileText]]
  return <section><div className="dashboard-page-heading"><div><p className="eyebrow">THEO DÕI & ĐIỀU PHỐI</p><h1>Báo cáo tổng quan</h1><p>Nắm quy mô hoạt động và những nội dung đang chờ xử lý.</p></div></div><ResourceState resource={resource}><div className="workspace-stats report-stats">{stats.map(([label,value,Icon]) => <article className="workspace-stat" key={label}><div><span>{label}</span><Icon size={20}/></div><strong>{Number(value || 0).toLocaleString('vi-VN')}</strong></article>)}</div><div className="workspace-grid"><section className="workspace-panel"><p className="eyebrow">TÌNH HÌNH THỰC TẬP</p><h2>Hồ sơ thực tập</h2>{[['Đang thực tập',data.internships?.active],['Đã hoàn thành',data.internships?.completed]].map(([label,value]) => <div className="report-bar" key={label}><div><span>{label}</span><b>{Number(value || 0)}</b></div><div className="report-bar-track"><span style={{width:`${Number(value || 0) / Math.max(1,Number(data.internships?.active || 0) + Number(data.internships?.completed || 0)) * 100}%`}}/></div></div>)}<p className="muted text-xs mt-5">Số lượng hồ sơ theo trạng thái hiện tại.</p></section><section className="workspace-panel"><p className="eyebrow">CẦN THEO DÕI</p><h2>Hàng chờ xử lý</h2><div className="workspace-task"><div><b>{data.companies?.pending || 0} doanh nghiệp chờ duyệt</b><p>Kiểm tra hồ sơ trước khi cho phép tuyển dụng.</p></div><Link className="text-link" to="/admin/companies">Mở<ArrowRight size={15}/></Link></div><div className="workspace-task"><div><b>{data.reportsPending || 0} báo cáo chờ duyệt</b><p>Theo dõi tiến độ phản hồi từ giảng viên.</p></div><Link className="text-link" to="/admin/applications">Theo dõi<ArrowRight size={15}/></Link></div></section></div></ResourceState></section>
}
