import { useState } from 'react'
import admin from '../../data/admin.json'

function Shell({ title, description, children }) { return <section><h1 className="text-2xl font-extrabold text-[#172d50]">{title}</h1><p className="mt-1 mb-5 text-sm text-[#7890ad]">{description}</p>{children}</section> }
export function AdminCompaniesPage() { const [companies, setCompanies] = useState(admin.pendingCompanies); function approve(id) { setCompanies(companies.map((x) => x.id === id ? { ...x, status: 'Đã duyệt' } : x)); } return <Shell title="Phê duyệt doanh nghiệp" description="Thẩm định hồ sơ và cấp quyền sử dụng hệ thống."><div className="space-y-4">{companies.map((company) => <article className="flex flex-wrap items-center justify-between gap-4 rounded-xl border border-[#e1eaf5] bg-white p-5" key={company.id}><div><h2 className="font-bold text-[#172d50]">{company.name}</h2><p className="mt-1 text-sm text-[#7890ad]">MST: {company.taxCode}</p></div><div className="flex items-center gap-3"><span className={`rounded-full px-3 py-1 text-xs font-bold ${company.status === 'Đã duyệt' ? 'bg-green-50 text-green-700' : 'bg-amber-50 text-amber-700'}`}>{company.status}</span>{company.status !== 'Đã duyệt' && <button onClick={() => approve(company.id)} className="rounded-md bg-[#0757c9] px-3 py-2 text-xs font-bold text-white" type="button">Duyệt</button>}</div></article>)}</div></Shell> }
export function AdminPeriodsPage() { const [periods, setPeriods] = useState(admin.periods); const [name, setName] = useState(''); function add(e) { e.preventDefault(); if (!name) return; setPeriods([...periods, { id: Date.now(), name, start: '2027-02-01', end: '2027-06-30', status: 'Bản nháp' }]); setName('') } return <Shell title="Quản lý kỳ thực tập" description="Thiết lập thời gian và trạng thái các kỳ đào tạo."><form onSubmit={add} className="mb-5 flex max-w-xl gap-2"><input className="min-w-0 flex-1 rounded-md border border-[#d8e3f0] px-3 py-2.5 text-sm" placeholder="Tên kỳ thực tập mới" value={name} onChange={(e) => setName(e.target.value)} /><button className="rounded-md bg-[#0757c9] px-4 py-2 text-sm font-bold text-white" type="submit">Thêm kỳ</button></form><div className="space-y-3">{periods.map((period) => <div className="rounded-xl border border-[#e1eaf5] bg-white p-5" key={period.id}><div className="flex justify-between gap-3"><h2 className="font-bold text-[#172d50]">{period.name}</h2><span className="text-xs font-bold text-[#0757c9]">{period.status}</span></div><p className="mt-2 text-sm text-[#7890ad]">{period.start} → {period.end}</p></div>)}</div></Shell> }
export function AdminUsersPage() { return <Shell title="Quản lý tài khoản" description="Quản lý tài khoản và phân quyền người dùng."><Empty text="Danh sách tài khoản sẽ được kết nối từ users.json và API quản trị." /></Shell> }
export function AdminAssignmentsPage() { return <Shell title="Phân công giảng viên" description="Gán giảng viên hướng dẫn cho hồ sơ thực tập."><Empty text="Chưa có yêu cầu phân công cần xử lý." /></Shell> }
export function AdminContentPage() { return <Shell title="Quản lý nội dung" description="Soạn thảo, duyệt và xuất bản nội dung trang thông tin."><Empty text="Chưa có bản nháp nội dung." /></Shell> }
export function AdminNotificationsPage() { return <Shell title="Quản lý thông báo" description="Tạo thông báo và chọn nhóm người nhận."><Empty text="Chưa có thông báo mới." /></Shell> }
export function AdminReportsPage() { return <Shell title="Báo cáo thống kê" description="Tổng hợp số liệu theo kỳ, khoa và doanh nghiệp."><div className="grid gap-4 sm:grid-cols-3">{[['Sinh viên','245'],['Doanh nghiệp','38'],['Hoàn thành','82%']].map(([label,value]) => <div className="rounded-xl border border-[#e1eaf5] bg-white p-5" key={label}><p className="text-sm text-[#7890ad]">{label}</p><p className="mt-2 text-3xl font-extrabold text-[#0757c9]">{value}</p></div>)}</div></Shell> }
function Empty({ text }) { return <div className="rounded-xl border border-dashed border-[#b9cee8] bg-white p-10 text-center text-sm text-[#7890ad]">{text}</div> }
